'use client';

export const dynamic = 'force-dynamic';

import React,{useCallback,useEffect,useMemo,useState}from'react';
import DashboardLayout from '@/components/DashboardLayout';
import{AlertTriangle,Edit3,ExternalLink,File,FileSpreadsheet,FileText,FolderOpen,Globe2,Loader2,Plus,RefreshCw,Search,ShieldCheck,Trash2,X}from'lucide-react';
import'./documents-v2.css';
import'./documents-edit.css';

interface DocumentItem{id:string;rowNumber:number;category:string;title:string;url:string;type:string;status:string;source:string;notes:string;updated:string;}
interface DocumentsSource{ok:boolean;source:string;mirrorSource?:string;canonical?:boolean;items:DocumentItem[];summary:{total:number;active:number;reference:number;categories:number};fetchedAt:string;}
type FormState={id:string;category:string;title:string;url:string;type:string;status:string;source:string;notes:string;};
const EMPTY:FormState={id:'',category:'General',title:'',url:'',type:'Google Drive',status:'Activo',source:'Drive',notes:''};
function iconFor(type:string){const n=type.toLowerCase();if(n.includes('sheet'))return FileSpreadsheet;if(n.includes('doc'))return FileText;if(n.includes('sitio')||n.includes('web'))return Globe2;return File;}
function formatDate(value:string){if(!value)return'Sin fecha';const date=new Date(`${value}T12:00:00`);if(Number.isNaN(date.getTime()))return value;return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric'}).format(date);}

export default function DocumentsPage(){
  const[data,setData]=useState<DocumentsSource|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[search,setSearch]=useState(''),[category,setCategory]=useState('Todos'),[editor,setEditor]=useState<FormState|null>(null),[previewMode,setPreviewMode]=useState(false),[notice,setNotice]=useState<string|null>(null),[saving,setSaving]=useState(false);
  useEffect(()=>setPreviewMode(window.location.hostname!=='gestion.felipeycami.cl'),[]);
  const loadData=useCallback(async(manual=false)=>{if(manual)setRefreshing(true);setError(null);try{const response=await fetch('/api/documents-source',{cache:'no-store'});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible cargar documentos.');setData(payload);}catch(err:any){setError(err?.message||'No fue posible cargar documentos.');}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{loadData();},[loadData]);
  const categories=useMemo(()=>['Todos',...Array.from(new Set((data?.items||[]).map(i=>i.category))).sort()],[data]);
  const filtered=useMemo(()=>{const term=search.toLowerCase().trim();return(data?.items||[]).filter(i=>{if(category!=='Todos'&&i.category!==category)return false;if(!term)return true;return`${i.title} ${i.category} ${i.type} ${i.status} ${i.notes}`.toLowerCase().includes(term);});},[data,search,category]);
  function newDocument(){setEditor({...EMPTY,id:`preview-${Date.now()}`});}
  function editDocument(item:DocumentItem){setEditor({id:item.id,category:item.category,title:item.title,url:item.url,type:item.type,status:item.status,source:item.source,notes:item.notes});}
  function localSave(form:FormState){setData(current=>{if(!current)return current;const exists=current.items.some(i=>i.id===form.id);const item:DocumentItem={...form,rowNumber:exists?(current.items.find(i=>i.id===form.id)?.rowNumber||1):current.items.length+1,updated:new Date().toISOString().slice(0,10)};const items=exists?current.items.map(i=>i.id===form.id?item:i):[item,...current.items];return{...current,items,summary:{total:items.length,active:items.filter(i=>i.status.toLowerCase()==='activo').length,reference:items.filter(i=>i.status.toLowerCase()==='referencia').length,categories:new Set(items.map(i=>i.category)).size}};});setEditor(null);setNotice('Documento guardado localmente en Preview.');}
  async function save(){if(!editor?.title.trim()){setError('El título es obligatorio.');return;}if(previewMode){localSave(editor);return;}setSaving(true);setError(null);try{const isNew=editor.id.startsWith('preview-');const response=await fetch('/api/documents-source',{method:isNew?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...editor,id:isNew?undefined:editor.id})});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.message||payload?.error||'No fue posible guardar.');setEditor(null);setNotice('Documento guardado.');await loadData();}catch(err:any){setError(err?.message||'No fue posible guardar.');}finally{setSaving(false);}}
  async function remove(item:DocumentItem){if(!window.confirm(`¿Eliminar “${item.title}”?`))return;if(previewMode){setData(current=>current?{...current,items:current.items.filter(i=>i.id!==item.id),summary:{...current.summary,total:current.summary.total-1}}:current);setNotice('Documento eliminado localmente en Preview.');return;}const response=await fetch(`/api/documents-source?id=${item.id}`,{method:'DELETE'});const payload=await response.json();if(!response.ok||!payload?.ok){setError(payload?.message||payload?.error||'No fue posible eliminar.');return;}await loadData();}

  return <DashboardLayout><div className="documents-v2">
    <section className="documents-v2__hero"><div><span className="documents-v2__eyebrow">Archivo operativo</span><h1>Documentos</h1><p>Registro canónico editable para contratos, planillas, minutas, links y fuentes del matrimonio.</p></div><div className="documents-v2__hero-actions">{previewMode&&<span className="documents-v2__preview">Preview · cambios locales</span>}<button type="button" onClick={()=>loadData(true)} disabled={refreshing}><RefreshCw size={14} className={refreshing?'animate-spin':''}/>{refreshing?'Actualizando…':'Actualizar'}</button><button type="button" className="is-primary" onClick={newDocument}><Plus size={14}/>Agregar documento</button></div></section>
    {error&&<div className="documents-v2__notice documents-v2__notice--error"><AlertTriangle size={16}/><span>{error}</span></div>}{notice&&<div className="documents-v2__notice"><ShieldCheck size={16}/><span>{notice}</span></div>}
    {loading?<div className="documents-v2__loading"><Loader2 className="animate-spin" size={21}/>Cargando registro documental…</div>:<>
      <section className="documents-v2__metrics"><article><span>Documentos registrados</span><strong>{data?.summary.total||0}</strong><small>en {data?.summary.categories||0} categorías</small></article><article><span>Fuentes activas</span><strong>{data?.summary.active||0}</strong><small>uso operativo actual</small></article><article><span>Referencias</span><strong>{data?.summary.reference||0}</strong><small>histórico / apoyo</small></article><article><span>Fuente canónica</span><strong>Supabase</strong><small>{data?.mirrorSource||'Registro documental'}</small></article></section>
      <section className="documents-v2__toolbar"><div className="documents-v2__search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar documento, categoría o nota…"/></div><div className="documents-v2__filters">{categories.map(item=><button key={item} type="button" className={category===item?'is-active':''} onClick={()=>setCategory(item)}>{item}</button>)}</div></section>
      <section className="documents-v2__grid">{filtered.map(item=>{const Icon=iconFor(item.type);const active=item.status.toLowerCase()==='activo';return <article key={item.id} className={active?'is-active':'is-reference'}><header><span className="documents-v2__icon"><Icon size={18}/></span><div className="documents-v2__card-actions"><span className={`documents-v2__status ${active?'is-active':''}`}>{item.status}</span><button onClick={()=>editDocument(item)} aria-label="Editar"><Edit3 size={13}/></button><button onClick={()=>remove(item)} aria-label="Eliminar"><Trash2 size={13}/></button></div></header><div className="documents-v2__category">{item.category}</div><h2>{item.title}</h2><p>{item.notes||'Sin nota operacional.'}</p><dl><div><dt>Tipo</dt><dd>{item.type}</dd></div><div><dt>Fuente</dt><dd>{item.source}</dd></div><div><dt>Actualizado</dt><dd>{formatDate(item.updated)}</dd></div></dl><footer>{item.url?<a href={item.url} target="_blank" rel="noreferrer"><FolderOpen size={14}/>Abrir fuente<ExternalLink size={12}/></a>:<span>Enlace pendiente</span>}</footer></article>;})}{!filtered.length&&<div className="documents-v2__empty">No hay documentos que coincidan con esta búsqueda.</div>}</section>
    </>}
    {editor&&<><button type="button" className="documents-v2__backdrop" aria-label="Cerrar" onClick={()=>!saving&&setEditor(null)}/><aside className="documents-v2__drawer"><header><div><span className="documents-v2__eyebrow">Registro documental</span><h2>{editor.id.startsWith('preview-')?'Agregar documento':'Editar documento'}</h2></div><button type="button" onClick={()=>setEditor(null)}><X size={18}/></button></header><div className="documents-v2__form"><label><span>Título *</span><input value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label><span>URL</span><input type="url" value={editor.url} onChange={e=>setEditor({...editor,url:e.target.value})} placeholder="https://…"/></label><div className="documents-v2__form-grid"><label><span>Categoría</span><input value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})}/></label><label><span>Tipo</span><select value={editor.type} onChange={e=>setEditor({...editor,type:e.target.value})}><option>Google Drive</option><option>Google Sheets</option><option>Google Docs</option><option>PDF</option><option>Sitio web</option><option>Otro</option></select></label></div><div className="documents-v2__form-grid"><label><span>Estado</span><select value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value})}><option>Activo</option><option>Referencia</option><option>Archivado</option></select></label><label><span>Fuente</span><input value={editor.source} onChange={e=>setEditor({...editor,source:e.target.value})}/></label></div><label><span>Notas</span><textarea rows={5} value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})}/></label><footer><button type="button" onClick={()=>setEditor(null)}>Cancelar</button><button type="button" className="is-primary" onClick={save} disabled={saving}>{saving?<Loader2 size={14} className="animate-spin"/>:null}Guardar</button></footer></div></aside></>}
  </div></DashboardLayout>;
}
