import * as PT from './client.js';
const card=document.querySelector('#card'),status=document.querySelector('#status'),q=new URLSearchParams(location.search),tableToken=q.get('m')||q.get('mesa')||'';let s;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(t,b){card.innerHTML='<div style="background:#f3efe7;border-radius:20px;padding:24px;margin-top:24px"><h2>'+t+'</h2>'+b+'</div>'}
function error(e){const el=document.querySelector('#err');if(el)el.textContent=({NICKNAME_TAKEN:'Ese nombre ya está usado en esta mesa. Prueba otro apodo.',TABLE_NOT_FOUND:'No encontramos esa mesa. Revisa el QR o código.',ROLE_TAKEN:'Ese rol ya fue tomado.'}[e.message]||'No pudimos completar eso. Intenta nuevamente.')}
function render(){status.textContent=s?.table?(s.table.team_name||'Mesa en preparación')+' · '+(s.table.score||0)+' pts':'El juego de las mesas';
if(!s?.player){shell('¿Cómo te llamas?','<p>Solo necesitamos tu nombre o apodo.</p><form id=f><input id=n required maxlength=32 placeholder="Tu nombre o apodo">'+(tableToken?'':'<input id=code required inputmode=numeric placeholder="Código de mesa">')+'<button>ENTRAR AL JUEGO</button><p id=err></p></form>');document.querySelector('#f').onsubmit=async e=>{e.preventDefault();try{s=await PT.join({tableToken:tableToken||undefined,tableCode:document.querySelector('#code')?.value,nickname:document.querySelector('#n').value});render()}catch(x){error(x)}};return}
if(!s.table.team_name&&!['complice','dupla'].includes(s.player.role)){shell('Ya estás en tu mesa.','<p>Todos pueden jugar. Dos personas pueden tomar las decisiones oficiales.</p><button id=c>Ser Cómplice</button> <button id=d>Ser Dupla</button><p id=err></p>');for(const [id,r] of [['c','complice'],['d','dupla']])document.querySelector('#'+id).onclick=async()=>{try{s=await PT.claimRole(r);render()}catch(x){error(x)}};return}
if(!s.table.team_name){shell('Pónganle nombre a su mesa.','<form id=f><input id=n required maxlength=32 placeholder="Los Inubicables"><button>CONFIRMAR</button><p id=err></p></form>');document.querySelector('#f').onsubmit=async e=>{e.preventDefault();try{s=await PT.teamName(document.querySelector('#n').value);render()}catch(x){error(x)}};return}
const st=s.stage;shell(esc(st?.payload?.title||st?.key?.replaceAll('-',' ')||'Por ahora, sigan disfrutando.'),st?'<p>'+esc(st.payload?.prompt||'Hablen entre ustedes. Plot Twist les avisará cuando haya que decidir algo.')+'</p>':'<p>No necesitan quedarse mirando el teléfono. Volveremos cuando pase algo.</p>')}
(async()=>{s=await PT.restore();render()})();addEventListener('online',async()=>{await PT.flush();s=await PT.restore();render()});