import * as PT from './client.js';
const card=document.querySelector('#card'),status=document.querySelector('#status'),q=new URLSearchParams(location.search),tableToken=q.get('m')||q.get('mesa')||'';let s,view='now';
const isResponsible=()=>['complice','dupla'].includes(s?.player?.role);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(t,b){card.innerHTML='<div style="background:#f3efe7;border-radius:20px;padding:24px;margin-top:24px"><h2>'+t+'</h2>'+b+'</div>'}
function error(e){const el=document.querySelector('#err');if(el)el.textContent=({NICKNAME_TAKEN:'Ese nombre ya está usado en esta mesa. Prueba otro apodo.',TABLE_NOT_FOUND:'No encontramos esa mesa. Revisa el QR o código.',ROLE_TAKEN:'Ya hay dos responsables en esta mesa.',RESPONSIBLE_SLOTS_FULL:'Ya hay dos responsables en esta mesa.'}[e.message]||'No pudimos completar eso. Intenta nuevamente.')}
async function renderNight(){const d=await PT.feed();shell('La noche',(d.events.length?d.events.map(e=>'<article><strong>'+esc(e.payload?.title||e.event_type)+'</strong><p>'+esc(e.payload?.text||'')+'</p><div><button class=rx data-id="'+esc(e.id)+'" data-e="😂">😂</button><button class=rx data-id="'+esc(e.id)+'" data-e="❤️">❤️</button><button class=rx data-id="'+esc(e.id)+'" data-e="🔥">🔥</button></div></article>').join(''):'<p>Todavía no hay momentos públicos. Vuelvan a disfrutar la mesa.</p>'));document.querySelectorAll('.rx').forEach(b=>b.onclick=async()=>{try{await PT.react(b.dataset.id,b.dataset.e);b.disabled=true}catch{}})}
async function renderTable(){const d=await PT.chronicle();const points=d.ledger.reduce((a,x)=>a+Number(x.delta||0),0);shell('Mi mesa','<p><strong>'+esc(s.table.team_name)+'</strong> · '+points+' pts</p><p>'+d.actions.length+' acciones · '+d.powers.filter(x=>x.status==='available').length+' poderes disponibles</p>'+d.ledger.slice(0,8).map(x=>'<p>'+((x.delta||0)>0?'+':'')+x.delta+' · '+esc(x.reason)+'</p>').join(''))}
function render(){document.querySelector('#nav').hidden=!s?.player;document.querySelector('#offline').classList.toggle('on',!navigator.onLine);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));status.textContent=s?.table?(s.table.team_name||'Mesa en preparación')+' · '+(s.table.score||0)+' pts':'El juego de las mesas';
if(s?.player&&view==='night'){renderNight();return}if(s?.player&&view==='table'){renderTable();return}
if(!s?.player){shell('¿Cómo te llamas?','<p>Solo necesitamos tu nombre o apodo.</p><form id=f><input id=n required maxlength=32 placeholder="Tu nombre o apodo">'+(tableToken?'':'<input id=code required inputmode=numeric placeholder="Código de mesa">')+'<button>ENTRAR AL JUEGO</button></form><button id=recover>¿Ya estabas jugando?</button><p id=err></p>');document.querySelector('#recover').onclick=async()=>{const code=tableToken?prompt('Ingresa el código corto impreso en tu mesa'):document.querySelector('#code')?.value;if(!code)return;try{const d=await PT.recoveryCandidates(code);shell('¿Quién eres?','<p>'+esc(d.table.team_name||'Tu mesa')+'</p>'+d.players.map(p=>'<button class=who data-id="'+esc(p.id)+'">'+esc(p.nickname)+'</button>').join('')+'<p id=err></p>');document.querySelectorAll('.who').forEach(b=>b.onclick=async()=>{try{s=await PT.recover(code,b.dataset.id);render()}catch(x){error(x)}})}catch(x){error(x)}};document.querySelector('#f').onsubmit=async e=>{e.preventDefault();try{s=await PT.join({tableToken:tableToken||undefined,tableCode:document.querySelector('#code')?.value,nickname:document.querySelector('#n').value});render()}catch(x){error(x)}};return}
if(!s.table.team_name&&!['complice','dupla'].includes(s.player.role)){shell('Ya estás en tu mesa.','<p>Todos pueden jugar. Solo necesitamos dos responsables para confirmar las decisiones oficiales.</p><button id=r>SER RESPONSABLE DE MESA</button><p id=err></p>');document.querySelector('#r').onclick=async()=>{try{s=await PT.claimResponsible();render()}catch(x){error(x)}};return}
if(!s.table.team_name){shell('Pónganle nombre a su mesa.','<form id=f><input id=n required maxlength=32 placeholder="Los Inubicables"><button>CONFIRMAR</button><p id=err></p></form>');document.querySelector('#f').onsubmit=async e=>{e.preventDefault();try{s=await PT.teamName(document.querySelector('#n').value);render()}catch(x){error(x)}};return}
const st=s.stage;if(!st){shell('Ahora','<p>No necesitan quedarse mirando el teléfono. Volveremos cuando pase algo.</p>');return}
const title=esc(st.payload?.title||st.key?.replaceAll('-',' ')||'Plot Twist'),prompt=esc(st.payload?.prompt||'Hablen entre ustedes. Plot Twist les avisará cuando haya que decidir algo.');
if(st.type==='individual_callback'&&st.status==='open'){const opts=(s.players||[]).filter(p=>p.id!==s.player.id).map(p=>'<button class=vote data-v="'+esc(p.id)+'">'+esc(p.nickname)+'</button>').join('');shell(title,'<p>'+prompt+'</p><p><strong>Esta vez no conversen.</strong> Tu respuesta es privada.</p>'+opts+'<p id=err></p>');document.querySelectorAll('.vote').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await PT.action(st.id,'individual_vote',{targetPlayerId:b.dataset.v});s=await PT.restore();shell('Voto guardado','<p>Listo. No mostraremos el resultado todavía.</p>')}catch(x){error(x)}});return}
if(st.type==='wager'&&st.status==='open'){const buttons=[.25,.5,1].map(v=>'<button class=wager data-v="'+v+'">'+(v*100)+'%</button>').join('');shell(title,'<p>'+prompt+'</p>'+(isResponsible()?buttons:'<p>Un responsable confirmará la apuesta.</p>')+'<p id=err></p>');if(isResponsible())document.querySelectorAll('.wager').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await PT.action(st.id,'wager',{fraction:Number(b.dataset.v)});s=await PT.restore();shell('Apuesta cerrada','<p>La decisión quedó guardada. Ya no se puede cambiar.</p>')}catch(x){error(x)}});return}
if(st.type==='table_decision'&&s.action){shell('Respuesta guardada','<p><strong>'+esc(s.action.payload?.answer||'Respuesta confirmada')+'</strong></p><p>Ya quedó registrada para esta mesa. Pueden cerrar el teléfono.</p>');return}
if(st.type==='table_decision'&&st.status==='open'){const opts=(st.payload?.options||['A','B','C','D']).map(o=>'<button class=ans data-v="'+esc(typeof o==='string'?o:o.value)+'">'+esc(typeof o==='string'?o:(o.label||o.value))+'</button>').join('');shell(title,'<p>'+prompt+'</p>'+(isResponsible()?'<div>'+opts+'</div><p id=err></p>':'<p><strong>Hablen todos.</strong> Un responsable confirmará la respuesta oficial.</p>'));if(isResponsible())document.querySelectorAll('.ans').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='ENVIANDO…';try{const r=await PT.action(st.id,'table_decision',{answer:b.dataset.v});s=r.snapshot||await PT.restore();shell('Respuesta confirmada','<p>Listo. Ya quedó guardada para '+esc(s.table.team_name)+'.</p>')}catch(x){error(x);render()}});return}
shell(title,'<p>'+prompt+'</p>'+(isResponsible()&&!s.table.ready?'<button id=ready>ESTAMOS LISTOS</button>':'') );const rb=document.querySelector('#ready');if(rb)rb.onclick=async()=>{rb.disabled=true;rb.textContent='GUARDANDO…';try{s=await PT.ready(true);render()}catch(x){error(x)}}}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
addEventListener('offline',()=>document.querySelector('#offline').classList.add('on'));
(async()=>{s=await PT.restore();render()})();addEventListener('online',async()=>{await PT.flush();s=await PT.restore();render()});