const scenes=[
{chapter:'PRÓLOGO',tag:'BIENVENIDOS',title:'Esta noche tiene un giro.',body:'20 mesas. Muchas historias. Una sola noche. Y algo que nadie sabe todavía.',action:'ENTRAR',project:'ESTA NOCHE TODO PUEDE CAMBIAR',guide:'La bienvenida es breve. Un QR por mesa; sin registro complicado.'},
{chapter:'MESA 08',tag:'TU EQUIPO',title:'Los Inubicables',body:'Ocho invitados, dos responsables. Todos participan. Una sola decisión oficial por mesa.',action:'CONOCER EL JUEGO',project:'20 MESAS · UNA HISTORIA',guide:'Todos pueden participar. Un teléfono por mesa también basta.'},
{chapter:'ROMPEHIELO',tag:'HABLEN ENTRE USTEDES',title:'Algo en común.',body:'Encuentren algo que todos compartan y que no sea conocer a los novios.',action:'ESTAMOS LISTOS',project:'EL MEJOR JUEGO OCURRE FUERA DE LA PANTALLA',guide:'No hay cronómetro agresivo. El teléfono invita a conversar.'},
{chapter:'PREGUNTA',tag:'FELIPE O CAMI',title:'¿Quién se atrevería primero?',body:'¿Quién propondría un viaje improvisado un jueves?',choices:['Felipe','Cami'],project:'¿QUÉ TAN BIEN LOS CONOCEN?',guide:'La respuesta se confirma por mesa. En esta demo los resultados son ficticios.'},
{chapter:'VOTO PRIVADO',tag:'ESTA VEZ NO CONVERSEN',title:'El último en pie.',body:'¿Quién de tu mesa seguirá bailando cuando todos se rindan?',choices:['Anto','Pipe','Javi','Nico'],project:'CADA MESA GUARDA UN SECRETO',guide:'Todos votan en privado. El resultado regresa más adelante como callback.'},
{chapter:'TÓMBOLA',tag:'MOMENTO EN VIVO',title:'El azar también juega.',body:'Una sola oportunidad. Un giro que puede cambiar la noche.',action:'GIRAR TÓMBOLA',project:'ES HORA DE UN PLOT TWIST',guide:'La tómbola aparece como uno de los pocos momentos sincronizados del salón.',theme:'dark',wheel:true},
{chapter:'PODER',tag:'PLOT TWIST',title:'Robo limitado.',body:'Un poder de alto impacto, pero con límites. Elijan a otra mesa.',choices:['Mesa 04 · Los Primos','Mesa 12 · Sin Señal','Mesa 17 · Los Tíos'],project:'NADIE ESTÁ A SALVO… PERO TODO TIENE LÍMITES',guide:'Los poderes reales requieren validación atómica en servidor.',theme:'wine'},
{chapter:'LA NOCHE',tag:'MOMENTOS',title:'La historia se escribe sola.',body:'Mesa 12 sobrevivió a un Plot Twist. La sala puede reaccionar.',choices:['😂','❤️','🔥'],project:'EL SALÓN TAMBIÉN PARTICIPA',guide:'Fotografías y reacciones son opcionales; nadie queda fuera por no subir fotos.'},
{chapter:'APUESTA',tag:'TODO O NADA',title:'¿Cuánto arriesgan?',body:'Elijan una parte del puntaje. La apuesta queda cerrada antes de ver la pregunta.',choices:['25%','50%','100%'],project:'TODO. O. NADA.',guide:'En el juego real el saldo se congela y sólo se modifica al resolver la respuesta.',theme:'dark'},
{chapter:'PREGUNTA FINAL',tag:'UNA ÚLTIMA DECISIÓN',title:'¿Qué guardarían de esta noche?',body:'Si Felipe y Cami pudieran conservar una sola cosa, ¿cuál sería?',choices:['Que todo fuera perfecto','Ver a su gente junta','La fiesta','Las fotos'],project:'LA ÚLTIMA PREGUNTA',guide:'La respuesta definitiva de los novios sigue pendiente de aprobación.',theme:'dark'},
{chapter:'BLOQUEO',tag:'YA NO HAY VUELTA ATRÁS',title:'Las decisiones están tomadas.',body:'Los puntos se cierran. Pero hay algo que las mesas todavía no saben.',action:'REVELAR',project:'CREYERON QUE HABÍA 20 EQUIPOS',guide:'La pantalla del salón toma el protagonismo; los celulares descansan.',theme:'wine'},
{chapter:'CAMPEONES',tag:'PREMIO VISIBLE',title:'Los Inubicables.',body:'Ganaron el marcador visible. El salón celebra.',action:'HAY ALGO MÁS',project:'TENEMOS UNA MESA CAMPEONA',guide:'El campeón se determina por ledger visible, no por votos arbitrarios.',theme:'dark'},
{chapter:'MESA DE LA NOCHE',tag:'EL VERDADERO GIRO',title:'Los Sin Señal.',body:'La mesa que hizo que la noche fuera mejor para todos.',action:'VER EL FINAL',project:'PLOT TWIST ESTABA MIRANDO OTRA COSA',guide:'Este segundo premio usa un puntaje secreto independiente del marcador visible.',theme:'wine'},
{chapter:'FINAL',tag:'FELIPE & CAMI · 23.10.26',title:'Siempre hubo uno solo.',body:'Creyeron que había 20 equipos. Siempre hubo uno solo: nuestra gente.',action:'VOLVER A EMPEZAR',project:'SIEMPRE HUBO UN SOLO EQUIPO: NUESTRA GENTE',guide:'Las piezas de cada mesa se unen. Agradecimientos, baile y fiesta.',theme:'dark'}
];let index=0,score=850,wager=0,selected='',spun=false,sound=false;const scene=document.querySelector('#scene'),projection=document.querySelector('#projection');function esc(v){return String(v).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]))}function paint(){const s=scenes[index];document.querySelector('#score').textContent=score.toLocaleString('es-CL')+' PTS';document.querySelector('#progress').textContent=(index+1)+' / '+scenes.length;document.querySelector('#chapter').textContent=s.chapter;document.querySelector('#guide').textContent=s.guide;scene.className='phone-body '+(s.theme||'');let choices=s.choices?'<div class="choices">'+s.choices.map(x=>'<button data-choice="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div>':'';scene.innerHTML='<div class="reveal"><div class="kicker">'+esc(s.tag)+'</div><h2>'+esc(s.title)+'</h2><p>'+esc(s.body)+'</p>'+(s.wheel?'<div class="wheel" id="wheel">✦</div>':'')+choices+(s.action?'<button class="primary" id="do">'+esc(s.action)+'</button>':'')+'<p class="hint">DEMO GUIADA · RESULTADOS ILUSTRATIVOS</p></div>';projection.innerHTML='<div class="project-mark">F<span>✦</span>C</div><p>'+esc(s.chapter)+'</p><h2 class="reveal">'+esc(s.project)+'</h2><small>FELIPE & CAMI · 23.10.26</small>';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{selected=b.dataset.choice;document.querySelectorAll('[data-choice]').forEach(x=>x.classList.toggle('selected',x===b));if(index===3)score+=300;if(index===6)score+=150;if(index===8)wager=Number(selected.replace('%',''))/100;if(index===9)score+=Math.round(score*wager);setTimeout(next,380)});const go=document.querySelector('#do');if(go)go.onclick=()=>{if(s.wheel&&!spun){spun=true;document.querySelector('#wheel').classList.add('spin');go.disabled=true;go.textContent='GIRANDO…';setTimeout(()=>{score+=500;go.disabled=false;go.textContent='+500 PUNTOS · CONTINUAR';go.onclick=next;document.querySelector('#score').textContent=score.toLocaleString('es-CL')+' PTS'},1800)}else next()}}function next(){if(index===scenes.length-1){index=0;score=850;wager=0;spun=false}else index++;paint()}document.querySelector('#next').onclick=next;document.querySelector('#prev').onclick=()=>{index=Math.max(0,index-1);paint()};document.querySelector('#restart').onclick=()=>{index=0;score=850;wager=0;spun=false;paint()};document.querySelector('#sound').onclick=()=>{sound=!sound;document.querySelector('#sound').textContent=sound?'♪ SONIDO ACTIVADO':'♪ SONIDO';};paint();