import crypto from 'crypto';
import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase-server';

export const dynamic = 'force-dynamic';

function formatPrivateKey(key:string){return key.replace(/\\n/g,'\n');}
function normalizeName(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}
async function googleAccessToken(email:string,privateKey:string){const now=Math.floor(Date.now()/1000);const header=Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT'})).toString('base64url');const claims=Buffer.from(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/spreadsheets.readonly',aud:'https://oauth2.googleapis.com/token',exp:now+3600,iat:now})).toString('base64url');const unsigned=`${header}.${claims}`;const signer=crypto.createSign('RSA-SHA256');signer.update(unsigned);const signature=signer.sign(formatPrivateKey(privateKey),'base64url');const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${unsigned}.${signature}`}),cache:'no-store'});if(!response.ok)throw new Error(`GOOGLE_OAUTH_FAILED_${response.status}`);const payload=await response.json();if(!payload.access_token)throw new Error('GOOGLE_OAUTH_TOKEN_MISSING');return payload.access_token as string;}
async function readRange(spreadsheetId:string,token:string,range:string){const response=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/${encodeURIComponent(range)}?majorDimension=ROWS`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!response.ok)throw new Error(`GOOGLE_SHEETS_READ_FAILED_${response.status}`);const payload=await response.json();return(payload.values||[])as string[][];}
const VALID_ATTENDANCE=new Set(['Asiste','No asiste']);
type MasterRecord={masterId:string;name:string;masterGroup:string;masterCategory:string;masterDietary:string;masterOrigin:string;masterStatus:string;masterConfirmationSource:string;masterAssignedTable:string;masterObservations:string;};

export async function GET(){
 try{
  const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({ok:false,error:'UNAUTHORIZED'},{status:401});const{data:profile}=await supabase.from('admin_profiles').select('active').eq('id',user.id).single();if(!profile?.active)return NextResponse.json({ok:false,error:'FORBIDDEN'},{status:403});
  const spreadsheetId=process.env.GOOGLE_SHEETS_SPREADSHEET_ID||'',email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL||'',key=process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY||'';if(!spreadsheetId||!email||!key)throw new Error('GOOGLE_SHEETS_NOT_CONFIGURED');const token=await googleAccessToken(email,key);
  const[confirmedRows,legacyGroupRows,masterRows,membersResult,relationshipGroupsResult,relationshipMembersResult]=await Promise.all([
   readRange(spreadsheetId,token,'CONFIRMADOS_ACTUALES!A1:J200'),readRange(spreadsheetId,token,'GRUPOS_MESA!A1:H200'),readRange(spreadsheetId,token,'BD_MAESTRA_INVITADOS!A1:N400'),
   supabase.from('rsvp_response_members').select('id, rsvp_id, display_name, guest_id, resolution_status, attendance_status, dietary_type, dietary_detail, updated_at').order('updated_at',{ascending:true}),
   supabase.from('guest_relationship_groups').select('*').eq('status','active').order('name'),supabase.from('guest_relationship_members').select('*').order('person_name')
  ]);if(membersResult.error)throw membersResult.error;
  const dataQuality:Array<{code:string;message:string;row?:number}>=[];
  const header=confirmedRows[0]||[];const looksLikeHeader=String(header[1]||'').trim()==='Asistencia'&&String(header[4]||'').trim()==='Estado de ficha';if(looksLikeHeader&&header[0]&&normalizeName(header[0])!=='nombre')dataQuality.push({code:'CONFIRMED_HEADER_NAME_OVERWRITE',message:`La celda A1 contiene “${header[0]}” en lugar del encabezado Nombre. Esa persona se recupera desde Supabase para no perderla.`,row:1});
  const masterRecords=masterRows.slice(1).filter(row=>String(row[1]||'').trim()).map((row):MasterRecord=>({masterId:String(row[0]||''),name:String(row[1]||'').trim(),masterGroup:String(row[2]||''),masterCategory:String(row[3]||''),masterDietary:String(row[4]||''),masterOrigin:String(row[5]||''),masterStatus:String(row[6]||''),masterConfirmationSource:String(row[7]||''),masterAssignedTable:String(row[11]||''),masterObservations:String(row[12]||'')}));
  const masterByName=new Map<string,MasterRecord>(),masterDuplicates=new Map<string,number>();masterRecords.forEach(record=>{const k=normalizeName(record.name);masterDuplicates.set(k,(masterDuplicates.get(k)||0)+1);if(!masterByName.has(k))masterByName.set(k,record);});const duplicateNames=Array.from(masterDuplicates.entries()).filter(([,n])=>n>1).map(([k])=>masterByName.get(k)?.name||k);if(duplicateNames.length)dataQuality.push({code:'MASTER_DUPLICATE_NAMES',message:`BD_MAESTRA_INVITADOS contiene ${duplicateNames.length} nombre(s) duplicados. Las relaciones no deben depender sólo del nombre en esos casos.`});const enrich=(name:string)=>masterByName.get(normalizeName(name))||null;
  const people=confirmedRows.map((row,index)=>({row,rowNumber:index+1})).filter(({row})=>Boolean(String(row[0]||'').trim())&&VALID_ATTENDANCE.has(String(row[1]||'').trim())).map(({row,rowNumber})=>{const name=String(row[0]||'').trim();return{rowNumber,name,attendance:String(row[1]||'').trim(),dietaryType:row[2]||'',dietaryDetail:row[3]||'',recordStatus:row[4]||'',guestId:row[5]||null,rsvpId:row[6]||null,confirmedAt:row[7]||null,syncStatus:row[8]||'',phone:row[9]||'',source:'confirmed_sheet' as const,...(enrich(name)||{})};});
  confirmedRows.forEach((row,index)=>{if(index===0&&looksLikeHeader)return;const name=String(row[0]||'').trim(),attendance=String(row[1]||'').trim();if(!name&&VALID_ATTENDANCE.has(attendance))dataQuality.push({code:'CONFIRMED_EMPTY_NAME',message:`Hay una fila marcada “${attendance}” sin nombre. No se cuenta hasta identificar a la persona.`,row:index+1});});
  const attending=people.filter(p=>p.attendance==='Asiste'),declined=people.filter(p=>p.attendance==='No asiste'),sheetAttendingNames=new Set(attending.map(p=>normalizeName(p.name))),sheetDeclinedNames=new Set(declined.map(p=>normalizeName(p.name))),members=membersResult.data||[];
  const incomingAttending=members.filter(m=>m.attendance_status==='attending'&&m.display_name&&!sheetAttendingNames.has(normalizeName(m.display_name))).map(m=>{const name=m.display_name||'';return{id:m.id,rsvpId:m.rsvp_id,name,guestId:m.guest_id||null,resolutionStatus:m.resolution_status||'unmatched',dietaryType:m.dietary_type||'',dietaryDetail:m.dietary_detail||'',updatedAt:m.updated_at||null,source:'supabase_pending_sheet' as const,...(enrich(name)||{})};});
  const incomingDeclined=members.filter(m=>m.attendance_status==='not_attending'&&m.display_name&&!sheetDeclinedNames.has(normalizeName(m.display_name))).map(m=>{const name=m.display_name||'';return{id:m.id,rsvpId:m.rsvp_id,name,guestId:m.guest_id||null,resolutionStatus:m.resolution_status||'unmatched',updatedAt:m.updated_at||null,source:'supabase_pending_sheet' as const,...(enrich(name)||{})};});
  const missingMaster=[...attending,...incomingAttending].filter((p:any)=>!p.masterId).map((p:any)=>p.name);if(missingMaster.length)dataQuality.push({code:'CONFIRMED_NOT_IN_MASTER_LIST',message:`${missingMaster.length} asistente(s) confirmado(s) no tienen coincidencia exacta en BD_MAESTRA_INVITADOS. Su clasificación debe revisarse manualmente.`});
  const associated=attending.filter(p=>p.recordStatus==='Ficha asociada'),withoutMasterRecord=attending.filter(p=>p.recordStatus==='Sin ficha maestra'),dietary=attending.filter(p=>p.dietaryType&&p.dietaryType!=='Ninguna'),incomingAssociated=incomingAttending.filter(p=>Boolean(p.guestId)),incomingWithoutMaster=incomingAttending.filter(p=>!p.guestId),incomingDietary=incomingAttending.filter(p=>p.dietaryType&&p.dietaryType!=='Ninguna'),latestSheet=attending[attending.length-1]||null,latestIncoming=incomingAttending[incomingAttending.length-1]||null;

  const legacyMembers=legacyGroupRows.slice(1).filter(row=>row[0]&&row[2]).map(row=>({groupId:row[0]||'',groupName:row[1]||'',person:row[2]||'',linkType:row[3]||'',sourceNote:row[7]||''}));
  const legacyGrouped=Array.from(legacyMembers.reduce((map,member)=>{const current=map.get(member.groupId)||{groupId:member.groupId,groupName:member.groupName,linkType:member.linkType,confirmed:member.linkType!=='Por validar',people:[]as string[],sourceNotes:[]as string[]};current.people.push(member.person);if(member.sourceNote&&!current.sourceNotes.includes(member.sourceNote))current.sourceNotes.push(member.sourceNote);if(member.linkType==='Por validar')current.confirmed=false;map.set(member.groupId,current);return map;},new Map<string,{groupId:string;groupName:string;linkType:string;confirmed:boolean;people:string[];sourceNotes:string[]}>()).values());
  const canonicalRows=relationshipGroupsResult.error?[]:(relationshipGroupsResult.data||[]),canonicalMembers=relationshipMembersResult.error?[]:(relationshipMembersResult.data||[]);
  const canonicalGrouped=canonicalRows.map((group:any)=>({groupId:group.external_key||group.id,groupName:group.name,linkType:group.link_type,confirmed:group.confidence==='confirmed',people:canonicalMembers.filter((member:any)=>member.group_id===group.id).map((member:any)=>member.person_name),sourceNotes:Array.from(new Set(canonicalMembers.filter((member:any)=>member.group_id===group.id).map((member:any)=>member.source_note).filter(Boolean))),canonicalId:group.id,confidence:group.confidence}));
  const grouped=canonicalGrouped.length?canonicalGrouped:legacyGrouped;const groupsSource=canonicalGrouped.length?'Supabase · guest_relationship_groups':'F&C Centro Comandos · GRUPOS_MESA';if(!canonicalGrouped.length)dataQuality.push({code:'RELATIONSHIPS_FALLBACK_SHEET',message:'No hay grupos canónicos disponibles; Seating Intelligence está usando GRUPOS_MESA como fallback de sólo lectura.'});
  const masterGroupCounts=[...attending,...incomingAttending].reduce((map:any,p:any)=>{const k=p.masterGroup||'Sin clasificar';map[k]=(map[k]||0)+1;return map;},{}as Record<string,number>);
  return NextResponse.json({ok:true,source:'F&C Centro Comandos · CONFIRMADOS_ACTUALES',liveSource:'Supabase · rsvp_response_members',groupsSource,legacyGroupsSource:'F&C Centro Comandos · GRUPOS_MESA',masterSource:'F&C Centro Comandos · BD_MAESTRA_INVITADOS',summary:{attending:attending.length,declined:declined.length,currentKnownAttending:attending.length+incomingAttending.length,currentKnownDeclined:declined.length+incomingDeclined.length,incomingAttending:incomingAttending.length,incomingDeclined:incomingDeclined.length,totalResponsesPeople:people.length,associated:associated.length,currentKnownAssociated:associated.length+incomingAssociated.length,withoutMasterRecord:withoutMasterRecord.length,currentKnownWithoutMaster:withoutMasterRecord.length+incomingWithoutMaster.length,dietary:dietary.length,currentKnownDietary:dietary.length+incomingDietary.length,latestConfirmationName:latestIncoming?.name||latestSheet?.name||null,latestConfirmationAt:latestIncoming?.updatedAt||latestSheet?.confirmedAt||null,dataQualityIssues:dataQuality.length,masterMetadataMatched:attending.length+incomingAttending.length-missingMaster.length,masterMetadataMissing:missingMaster.length,canonicalRelationshipGroups:canonicalGrouped.length},people,incomingAttending,incomingDeclined,groups:grouped,masterGroupCounts,dataQuality,fetchedAt:new Date().toISOString()});
 }catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible leer confirmados y grupos.'},{status:500});}
}
