'use client';

import React,{useEffect,useMemo,useState}from'react';
import Link from'next/link';
import{usePathname}from'next/navigation';
import{Activity,AlertCircle,CalendarDays,DollarSign,ExternalLink,FileText,Grid,HeartPulse,LayoutDashboard,LogOut,Menu,Music,RefreshCw,Sparkles,Users,X}from'lucide-react';
import type{LucideIcon}from'lucide-react';
import{createClient}from'@/lib/supabase-browser';
import PlanningCopilot from'@/components/PlanningCopilot';
import VenueEditController from'@/components/VenueEditController';
import VenueSeatingDraftDock from'@/components/VenueSeatingDraftDock';
import SeatingIntelligenceDock from'@/components/SeatingIntelligenceDock';
import ManualTasksDock from'@/components/ManualTasksDock';
import GuestQuickEditorDock from'@/components/GuestQuickEditorDock';
import RelationshipEditorDock from'@/components/RelationshipEditorDock';

interface LayoutProps{children:React.ReactNode;}type NavItem={label:string;href:string;icon:LucideIcon;description:string;};
const navigationGroups:Array<{label:string;items:NavItem[]}>= [
{label:'Control',items:[{label:'Inicio',href:'/dashboard',icon:LayoutDashboard,description:'Estado general de la boda'},{label:'Necesita atención',href:'/dashboard/issues',icon:AlertCircle,description:'Incidencias por resolver'},{label:'Planificación',href:'/dashboard/planning',icon:CalendarDays,description:'Plan de cierre desde datos reales'},{label:'Estado del sistema',href:'/dashboard/system',icon:HeartPulse,description:'Fuentes, integridad y seguridad'}]},
{label:'Personas y espacio',items:[{label:'Invitados',href:'/dashboard/guests',icon:Users,description:'Personas, RSVP y restricciones'},{label:'Mesas',href:'/dashboard/tables',icon:Grid,description:'Grupos, asignación y capacidad'},{label:'Salón',href:'/dashboard/venue',icon:Grid,description:'Plano a escala y montaje'}]},
{label:'Operación',items:[{label:'Equipo y proveedores',href:'/dashboard/team',icon:Users,description:'Foto, AV, sonido, músicos y montaje'},{label:'Cronograma',href:'/dashboard/timeline',icon:CalendarDays,description:'Secuencia operativa del evento'},{label:'Música',href:'/dashboard/music',icon:Music,description:'DJ, músicos, sets y canciones'},{label:'Presupuesto',href:'/dashboard/finance',icon:DollarSign,description:'Gastos, pagos y contratos'},{label:'Documentos',href:'/dashboard/documents',icon:FileText,description:'Fuentes activas y referencias'},{label:'Actividad',href:'/dashboard/activity',icon:Activity,description:'Historial de cambios'}]},
];
const routeTitles:Record<string,{eyebrow:string;title:string}>={'/dashboard':{eyebrow:'Centro de Gestión',title:'Inicio'},'/dashboard/issues':{eyebrow:'Control',title:'Necesita atención'},'/dashboard/planning':{eyebrow:'Control',title:'Planificación'},'/dashboard/system':{eyebrow:'Control',title:'Estado del sistema'},'/dashboard/guests':{eyebrow:'Personas',title:'Invitados'},'/dashboard/tables':{eyebrow:'Espacio',title:'Mesas'},'/dashboard/venue':{eyebrow:'Espacio',title:'Salón'},'/dashboard/team':{eyebrow:'Producción',title:'Equipo y proveedores'},'/dashboard/timeline':{eyebrow:'Operación',title:'Cronograma'},'/dashboard/music':{eyebrow:'Experiencia',title:'Música'},'/dashboard/finance':{eyebrow:'Operación',title:'Presupuesto'},'/dashboard/documents':{eyebrow:'Operación',title:'Documentos'},'/dashboard/activity':{eyebrow:'Trazabilidad',title:'Actividad'}};
function getDaysUntilWedding(){const wedding=new Date('2026-10-23T17:30:00-03:00');return Math.max(0,Math.ceil((wedding.getTime()-Date.now())/86_400_000));}

export default function DashboardLayout({children}:LayoutProps){
 const pathname=usePathname();const[userEmail,setUserEmail]=useState('Cargando…'),[userRole,setUserRole]=useState(''),[syncing,setSyncing]=useState(false),[mobileOpen,setMobileOpen]=useState(false);
 const pageContext=useMemo(()=>{if(!pathname)return routeTitles['/dashboard'];const exact=routeTitles[pathname];if(exact)return exact;const parent=Object.keys(routeTitles).filter(r=>r!=='/dashboard'&&pathname.startsWith(r)).sort((a,b)=>b.length-a.length)[0];return routeTitles[parent]||routeTitles['/dashboard'];},[pathname]);const daysUntilWedding=useMemo(()=>getDaysUntilWedding(),[]);useEffect(()=>setMobileOpen(false),[pathname]);
 useEffect(()=>{(async()=>{try{const supabase=createClient(),{data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/login';return;}setUserEmail(user.email||'Administrador');const{data:profile}=await supabase.from('admin_profiles').select('role').eq('id',user.id).single();setUserRole(profile?.role||'administrador');}catch(e){console.error('Error checking auth:',e);}})();},[]);
 async function handleSignOut(){try{const supabase=createClient();await supabase.auth.signOut();}finally{window.location.href='/login';}}
 async function handleSyncNow(){setSyncing(true);try{const r=await fetch('/api/sync/process',{method:'POST'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||d.error||'No fue posible sincronizar.');window.alert(`Sincronización completada. Registros procesados: ${d.processed||0}.`);}catch(e:any){window.alert(e?.message||'No fue posible sincronizar.');}finally{setSyncing(false);}}
 const sidebarContent=<><div className="workspace-sidebar-scroll"><div className="workspace-brand"><div className="workspace-brand-lockup"><span className="workspace-mark">F&amp;C</span><div><strong>Centro de Gestión</strong><span>Felipe &amp; Camila</span></div></div><button className="workspace-sidebar-close" onClick={()=>setMobileOpen(false)}><X size={19}/></button></div><div className="workspace-event-card"><div className="workspace-event-kicker"><span>23 octubre 2026</span><span>{daysUntilWedding===0?'Hoy':`${daysUntilWedding} días`}</span></div><strong>El Umbral Vivo</strong><p>Una sola vista para decisiones, personas, espacio y operación.</p><div className="workspace-event-progress"><span/></div></div><nav className="workspace-nav">{navigationGroups.map(group=><div className="workspace-nav-group" key={group.label}><span className="workspace-nav-label">{group.label}</span><div className="workspace-nav-list">{group.items.map(item=>{const Icon=item.icon,active=pathname===item.href||(item.href!=='/dashboard'&&pathname?.startsWith(item.href));return<Link key={item.href} href={item.href} className={`workspace-nav-item ${active?'is-active':''}`}><span className="workspace-nav-icon"><Icon size={18} strokeWidth={1.8}/></span><span className="workspace-nav-copy"><strong>{item.label}</strong><small>{item.description}</small></span></Link>;})}</div></div>)}</nav></div><div className="workspace-sidebar-footer"><button className="workspace-assistant-status" onClick={()=>window.dispatchEvent(new CustomEvent('fc-open-copilot'))}><span className="workspace-assistant-icon"><Sparkles size={16}/></span><div><strong>Copiloto operacional</strong><small>GPT + datos conectados</small></div></button><div className="workspace-footer-actions"><button onClick={handleSyncNow} disabled={syncing} className="workspace-sync-button"><RefreshCw size={15} className={syncing?'animate-spin':''}/><span>{syncing?'Sincronizando…':'Sincronizar datos'}</span></button><a href="https://felipeycami.cl" target="_blank" rel="noreferrer" className="workspace-invite-link"><ExternalLink size={14}/><span>Ver invitación</span></a></div><div className="workspace-profile"><div className="workspace-avatar">{userEmail?.slice(0,1).toUpperCase()||'F'}</div><div className="workspace-profile-copy"><strong>{userEmail}</strong><span>{userRole||'administrador'}</span></div><button onClick={handleSignOut}><LogOut size={16}/></button></div></div></>;
 return<div className="workspace-shell"><header className="workspace-mobile-topbar"><button onClick={()=>setMobileOpen(true)}><Menu size={21}/></button><div><span>F&amp;C</span><small>{pageContext.title}</small></div><span className="workspace-mobile-days">{daysUntilWedding}d</span></header>{mobileOpen&&<button className="workspace-backdrop" onClick={()=>setMobileOpen(false)}/>}<aside className={`workspace-sidebar ${mobileOpen?'is-open':''}`}>{sidebarContent}</aside><main className="workspace-main"><header className="workspace-contextbar"><div><span>{pageContext.eyebrow}</span><strong>{pageContext.title}</strong></div><div className="workspace-context-meta"><span>23 · 10 · 26</span><span className="workspace-context-dot"/><span>{daysUntilWedding===0?'Hoy es el día':`Faltan ${daysUntilWedding} días`}</span></div></header><div className="workspace-main-inner">{children}</div></main>{pathname?.startsWith('/dashboard/venue')&&<><VenueEditController/><VenueSeatingDraftDock/></>}{pathname?.startsWith('/dashboard/tables')&&<SeatingIntelligenceDock/>}{pathname?.startsWith('/dashboard/planning')&&<ManualTasksDock/>}{pathname?.startsWith('/dashboard/guests')&&<><GuestQuickEditorDock/><RelationshipEditorDock/></>}<PlanningCopilot currentPath={pathname||'/dashboard'}/></div>;
}
