'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, CheckCircle2, Circle, Edit3, ListTodo, Loader2, Plus, Save, Trash2, X } from 'lucide-react';
import styles from './ManualTasksDock.module.css';

type Task = {
  id:string; title:string; description:string; category:string; owner:string; status:string; priority:string;
  dueAt:string|null; source:string; completedAt:string|null; createdAt?:string; updatedAt?:string;
};
type Form = Omit<Task,'completedAt'|'createdAt'|'updatedAt'>;
const KEY='fc-preview-manual-tasks-v1';
const EMPTY:Form={id:'',title:'',description:'',category:'General',owner:'Felipe & Camila',status:'Pendiente',priority:'Media',dueAt:null,source:'manual'};

function readLocal(){try{const parsed=JSON.parse(window.localStorage.getItem(KEY)||'[]');return Array.isArray(parsed)?parsed:[];}catch{return[];}}
function writeLocal(tasks:Task[]){try{window.localStorage.setItem(KEY,JSON.stringify(tasks.slice(-250)));}catch{/* optional */}}
function dueLabel(value:string|null){if(!value)return'Sin fecha';try{return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(new Date(value));}catch{return value;}}

export default function ManualTasksDock(){
  const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[tasks,setTasks]=useState<Task[]>([]),[editor,setEditor]=useState<Form|null>(null),[error,setError]=useState<string|null>(null),[preview,setPreview]=useState(false);
  useEffect(()=>setPreview(window.location.hostname!=='gestion.felipeycami.cl'),[]);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch('/api/tasks',{cache:'no-store'});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible leer las tareas.');let next=(payload.tasks||[]) as Task[];if(window.location.hostname!=='gestion.felipeycami.cl'){const local=readLocal();const byId=new Map(next.map(task=>[task.id,task]));local.forEach((task:Task)=>byId.set(task.id,task));next=Array.from(byId.values());}setTasks(next);}catch(err:any){setError(err?.message||'No fue posible leer las tareas.');}finally{setLoading(false);}},[]);
  useEffect(()=>{if(open)void load();},[open,load]);
  const pending=useMemo(()=>tasks.filter(task=>task.status!=='Completada').sort((a,b)=>{const p:Record<string,number>={Alta:0,Media:1,Baja:2};return(p[a.priority]??1)-(p[b.priority]??1)||String(a.dueAt||'9999').localeCompare(String(b.dueAt||'9999'));}),[tasks]);
  const completed=tasks.filter(task=>task.status==='Completada').length;
  function create(){setEditor({...EMPTY,id:`preview-task-${Date.now()}`});}
  function edit(task:Task){setEditor({id:task.id,title:task.title,description:task.description,category:task.category,owner:task.owner,status:task.status,priority:task.priority,dueAt:task.dueAt,source:task.source});}
  function localUpsert(form:Form){const task:Task={...form,completedAt:form.status==='Completada'?new Date().toISOString():null,updatedAt:new Date().toISOString()};setTasks(current=>{const exists=current.some(item=>item.id===task.id);const next=exists?current.map(item=>item.id===task.id?task:item):[...current,task];writeLocal(next.filter(item=>item.id.startsWith('preview-task-')));return next;});setEditor(null);}
  async function save(){if(!editor?.title.trim()){setError('El título es obligatorio.');return;}if(preview){localUpsert(editor);return;}setSaving(true);setError(null);try{const isNew=editor.id.startsWith('preview-task-');const response=await fetch('/api/tasks',{method:isNew?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...editor,id:isNew?undefined:editor.id})});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible guardar la tarea.');setEditor(null);await load();}catch(err:any){setError(err?.message||'No fue posible guardar la tarea.');}finally{setSaving(false);}}
  async function toggle(task:Task){const status=task.status==='Completada'?'Pendiente':'Completada';if(preview){localUpsert({id:task.id,title:task.title,description:task.description,category:task.category,owner:task.owner,status,priority:task.priority,dueAt:task.dueAt,source:task.source});return;}const response=await fetch('/api/tasks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:task.id,status})});if(response.ok)await load();}
  async function remove(task:Task){if(!window.confirm(`¿Eliminar “${task.title}”?`))return;if(preview){setTasks(current=>{const next=current.filter(item=>item.id!==task.id);writeLocal(next.filter(item=>item.id.startsWith('preview-task-')));return next;});return;}const response=await fetch(`/api/tasks?id=${task.id}`,{method:'DELETE'});if(response.ok)await load();}

  return <><button type="button" className={styles.fab} onClick={()=>setOpen(value=>!value)}>{open?<X size={17}/>:<><ListTodo size={16}/><span>Tareas</span>{pending.length>0&&<b>{pending.length}</b>}</>}</button>{open&&<aside className={styles.panel}>
    <header><div><span>Planificación manual</span><strong>Tareas del matrimonio</strong><small>{pending.length} pendientes · {completed} completadas{preview?' · Preview persistente':''}</small></div><button onClick={()=>setOpen(false)}><X size={16}/></button></header>
    <div className={styles.actions}><button onClick={create}><Plus size={13}/>Nueva tarea</button><span>Estas tareas complementan las prioridades automáticas.</span></div>
    {error&&<div className={styles.error}>{error}</div>}
    {loading?<div className={styles.loading}><Loader2 size={18} className="animate-spin"/>Cargando tareas…</div>:<div className={styles.list}>{pending.map(task=><article key={task.id}><button className={styles.check} onClick={()=>toggle(task)}><Circle size={16}/></button><div><span>{task.category} · {task.priority}</span><strong>{task.title}</strong>{task.description&&<p>{task.description}</p>}<small>{task.owner||'Sin responsable'} · {dueLabel(task.dueAt)}</small></div><div className={styles.rowActions}><button onClick={()=>edit(task)}><Edit3 size={12}/></button><button onClick={()=>remove(task)}><Trash2 size={12}/></button></div></article>)}{!pending.length&&<div className={styles.empty}><CheckCircle2 size={20}/><strong>No hay tareas manuales pendientes.</strong><span>Puedes crear una para cualquier detalle que el plan automático no cubra.</span></div>}{tasks.filter(task=>task.status==='Completada').map(task=><article key={task.id} className={styles.done}><button className={styles.check} onClick={()=>toggle(task)}><Check size={16}/></button><div><span>{task.category}</span><strong>{task.title}</strong><small>Completada</small></div><div className={styles.rowActions}><button onClick={()=>edit(task)}><Edit3 size={12}/></button></div></article>)}</div>}
    {editor&&<div className={styles.editor}><div className={styles.editorHead}><strong>{editor.id.startsWith('preview-task-')?'Nueva tarea':'Editar tarea'}</strong><button onClick={()=>setEditor(null)}><X size={14}/></button></div><label><span>Título *</span><input value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label><span>Descripción</span><textarea rows={3} value={editor.description} onChange={e=>setEditor({...editor,description:e.target.value})}/></label><div className={styles.grid}><label><span>Categoría</span><input value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})}/></label><label><span>Responsable</span><input value={editor.owner} onChange={e=>setEditor({...editor,owner:e.target.value})}/></label></div><div className={styles.grid}><label><span>Prioridad</span><select value={editor.priority} onChange={e=>setEditor({...editor,priority:e.target.value})}><option>Alta</option><option>Media</option><option>Baja</option></select></label><label><span>Estado</span><select value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value})}><option>Pendiente</option><option>En curso</option><option>Completada</option></select></label></div><label><span>Fecha límite</span><input type="datetime-local" value={editor.dueAt?String(editor.dueAt).slice(0,16):''} onChange={e=>setEditor({...editor,dueAt:e.target.value||null})}/></label><footer><button onClick={()=>setEditor(null)}>Cancelar</button><button className={styles.primary} onClick={save} disabled={saving}>{saving?<Loader2 size={13} className="animate-spin"/>:<Save size={13}/>}Guardar</button></footer></div>}
  </aside>}</>;
}
