'use client';

import React,{useEffect,useMemo,useState}from'react';
import Link from'next/link';
import{ArrowRight,Bot,Check,Loader2,MessageCircle,Send,Sparkles,X}from'lucide-react';
import{createClient}from'@/lib/supabase-browser';
import{normalizeOperationalText,parseOperationalAction,type OperationalAction,type OperationalActionType}from'@/lib/copilot-operations';
import{mergePreviewEntities,readPreviewEntityState,removePreviewEntity,upsertPreviewEntity,writePreviewEntityState}from'@/lib/preview-entity-state';
import styles from'./PlanningCopilot.module.css';

type CopilotProps={currentPath:string};
type ActionType=OperationalActionType;
type CopilotAction=OperationalAction;
type Message={role:'assistant'|'user';text:string;meta?:string;action?:CopilotAction;actionState?:'pending'|'applied'|'discarded'|'error'};
type PreviewGuestState={overrides:Record<string,any>;deleted:string[]};
type PreviewTableState={overrides:Record<string,any>;created:any[];deleted:string[];assignments:Record<string,string|null>};
type PreviewFinanceState={budget:Record<string,any>;vendors:Record<string,any>;payments:Record<string,any>;deleted:{budget:string[];vendors:string[];payments:string[]}};

const PANEL_ID='copilot';
const CHAT_KEY='fc-copilot-chat-v6',PREVIEW_GUESTS_KEY='fc-preview-guests-v1',PREVIEW_MUSIC_KEY='fc-preview-music-actions-v1',PREVIEW_TIMELINE_KEY='fc-preview-timeline-actions-v1',PREVIEW_TASK_KEY='fc-preview-manual-tasks-v1',PREVIEW_MEMORY_KEY='fc-preview-memory-v1',PREVIEW_TABLES_KEY='fc-preview-tables-v2',PREVIEW_FINANCE_KEY='fc-preview-finance-v1';

function normalize(value:string){return normalizeOperationalText(value);}
function fullName(guest:any){return`${guest.first_name||''} ${guest.last_name||''}`.trim();}
function modeLabel(payload:any){if(payload.mode==='openai-responses-tools')return`${payload.model} · IA + herramientas · datos consultados ahora`;if(payload.mode==='ai-gateway')return`${payload.model} · AI Gateway · datos consultados ahora`;if(payload.mode==='grounded-delta')return'Revisión comparativa · datos consultados ahora';if(payload.mode==='operational-engine')return payload.aiError?'Motor operacional activo · IA externa no disponible':'Motor operacional costo 0 · datos consultados ahora';return payload.aiError?'Motor operacional activo · proveedor IA externo no configurado':'Motor operacional · respuesta basada en datos reales';}
function destination(type:ActionType){if(type.startsWith('guest.'))return'Invitados';if(type.startsWith('seating.')||type.startsWith('table.'))return'Mesas / Salón';if(type.startsWith('music.'))return'Música';if(type.startsWith('timeline.'))return'Cronograma';if(type.startsWith('task.'))return'Planificación';if(type==='memory.create')return'Memoria IA';if(type.startsWith('budget.')||type.startsWith('vendor.')||type.startsWith('payment.'))return'Presupuesto y proveedores';return'Centro de Gestión';}
function readGuestPreview():PreviewGuestState{try{const parsed=JSON.parse(localStorage.getItem(PREVIEW_GUESTS_KEY)||'null');return parsed?.overrides?parsed:{overrides:{},deleted:[]};}catch{return{overrides:{},deleted:[]};}}
function writeGuestPreview(state:PreviewGuestState){localStorage.setItem(PREVIEW_GUESTS_KEY,JSON.stringify(state));dispatchEvent(new CustomEvent('fc-preview-guests-changed'));}
function readTablePreview():PreviewTableState{try{const parsed=JSON.parse(localStorage.getItem(PREVIEW_TABLES_KEY)||'null');return parsed?.assignments?parsed:{overrides:{},created:[],deleted:[],assignments:{}};}catch{return{overrides:{},created:[],deleted:[],assignments:{}};}}
function writeTablePreview(state:PreviewTableState){localStorage.setItem(PREVIEW_TABLES_KEY,JSON.stringify(state));dispatchEvent(new CustomEvent('fc-preview-tables-changed'));}
function readFinancePreview():PreviewFinanceState{try{const parsed=JSON.parse(localStorage.getItem(PREVIEW_FINANCE_KEY)||'null');return parsed?.deleted?parsed:{budget:{},vendors:{},payments:{},deleted:{budget:[],vendors:[],payments:[]}};}catch{return{budget:{},vendors:{},payments:{},deleted:{budget:[],vendors:[],payments:[]}};}}
function writeFinancePreview(state:PreviewFinanceState){localStorage.setItem(PREVIEW_FINANCE_KEY,JSON.stringify(state));dispatchEvent(new CustomEvent('fc-preview-finance-changed'));}
function uniqueMatch(items:any[],target:string,fields:(item:any)=>string[],label:string){const q=normalize(target),exact=items.filter(item=>fields(item).some(value=>normalize(value)===q));if(exact.length===1)return exact[0];if(exact.length>1)throw new Error(`Encontré más de un ${label} para “${target}”. Usa un nombre más específico.`);const partial=items.filter(item=>fields(item).some(value=>{const n=normalize(value);return n&&(n.includes(q)||q.includes(n));}));if(partial.length===1)return partial[0];throw new Error(partial.length?`Hay varios ${label}s que podrían ser “${target}”. Necesito un nombre más específico.`:`No encontré ${label} “${target}”.`);}

export default function PlanningCopilot({currentPath}:CopilotProps){
 const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([{role:'assistant',text:'Soy el Copiloto Operacional. Puedo consultar el estado real y preparar cambios confirmables en invitados, mesas, salón, música, cronograma, tareas, presupuesto, pagos y proveedores.'}]);
 const previewMode=typeof window!=='undefined'&&location.hostname!=='gestion.felipeycami.cl';
 const pageLabel=useMemo(()=>currentPath.includes('/guests')?'Invitados':currentPath.includes('/tables')?'Mesas':currentPath.includes('/venue')?'Salón':currentPath.includes('/team')?'Equipo y proveedores':currentPath.includes('/finance')?'Presupuesto':currentPath.includes('/timeline')?'Cronograma':currentPath.includes('/music')?'Música':currentPath.includes('/memory')?'Memoria IA':currentPath.includes('/documents')?'Documentos':currentPath.includes('/planning')?'Planificación':currentPath.includes('/system')?'Estado del sistema':currentPath.includes('/issues')?'Necesita atención':'Inicio',[currentPath]);
 useEffect(()=>{const announce=()=>{dispatchEvent(new CustomEvent('fc-workspace-panel-open',{detail:PANEL_ID}));dispatchEvent(new CustomEvent('fc-management-overlay-open',{detail:PANEL_ID}));};const handler=()=>{announce();setOpen(true);};const exclusive=(event:Event)=>{if((event as CustomEvent).detail!==PANEL_ID)setOpen(false);};addEventListener('fc-open-copilot',handler);addEventListener('fc-workspace-panel-open',exclusive);addEventListener('fc-management-overlay-open',exclusive);try{const stored=sessionStorage.getItem(CHAT_KEY);if(stored){const parsed=JSON.parse(stored);if(Array.isArray(parsed)&&parsed.length)setMessages(parsed.slice(-50));}}catch{}return()=>{removeEventListener('fc-open-copilot',handler);removeEventListener('fc-workspace-panel-open',exclusive);removeEventListener('fc-management-overlay-open',exclusive);};},[]);
 useEffect(()=>{try{sessionStorage.setItem(CHAT_KEY,JSON.stringify(messages.slice(-50)));}catch{}},[messages]);
 function toggle(){setOpen(current=>{const next=!current;if(next){dispatchEvent(new CustomEvent('fc-workspace-panel-open',{detail:PANEL_ID}));dispatchEvent(new CustomEvent('fc-management-overlay-open',{detail:PANEL_ID}));}return next;});}
 async function submit(question=input){const text=question.trim();if(!text||loading)return;const localAction=parseOperationalAction(text);setMessages(cur=>[...cur,{role:'user',text}]);setInput('');if(localAction){setMessages(cur=>[...cur,{role:'assistant',text:`Preparé “${localAction.label}”. Revisa el detalle y confirma para aplicarlo.`,meta:'Motor operativo costo 0 · acción confirmable',action:localAction,actionState:'pending'}]);return;}const history=messages.filter(m=>!m.action||m.actionState!=='pending').slice(-12).map(({role,text})=>({role,text}));setLoading(true);try{const r=await fetch('/api/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:text,currentPath,history})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.message||p?.error||'No pude consultar el evento.');setMessages(cur=>[...cur,{role:'assistant',text:p.answer,meta:modeLabel(p),action:p.action||undefined,actionState:p.action?'pending':undefined}]);}catch(e:any){setMessages(cur=>[...cur,{role:'assistant',text:e?.message||'No pude responder en este momento.',meta:'Copiloto no disponible'}]);}finally{setLoading(false);}}
 function updateActionState(id:string,state:Message['actionState'],text?:string){setMessages(cur=>cur.map(m=>m.action?.id===id?{...m,actionState:state,...(text?{text:`${m.text}\n\n${text}`}:{})}:m));}
 function appendLocal(key:string,draft:any,limit=150){try{const cur=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([...(Array.isArray(cur)?cur:[]),draft].slice(-limit)));}catch{}}
 function savePreviewGuest(action:CopilotAction){const state=readGuestPreview(),id=`preview-guest-${Date.now()}`;state.overrides[id]={id,first_name:action.payload.first_name||'Nuevo',last_name:action.payload.last_name||'',phone_e164:null,group_name:action.payload.group_name||'Por clasificar',family_side:action.payload.family_side||'Por clasificar',family_branch:null,guest_category:action.payload.guest_category||'Adulto',invitation_status:'not_sent',attendance_status:action.payload.attendance_status||'pending',dietary_type:'Ninguna',dietary_detail:null,reconfirmation_status:'pending',table_id:null,rsvp_id:null,guest_status:'active',notes:action.payload.notes||'Borrador creado desde Copiloto'};writeGuestPreview(state);}
 function savePreviewStandard(action:CopilotAction){if(action.type==='guest.create'){savePreviewGuest(action);return;}if(action.type==='task.create'){const draft={id:`preview-task-${Date.now()}`,title:action.payload.title||'Nueva tarea',description:action.payload.description||'',category:action.payload.category||'General',owner:action.payload.owner||'Felipe & Camila',status:action.payload.status||'Pendiente',priority:action.payload.priority||'Media',dueAt:action.payload.dueAt||null,source:'copilot-preview',completedAt:null,updatedAt:new Date().toISOString()};const state=upsertPreviewEntity(readPreviewEntityState<any>(PREVIEW_TASK_KEY),draft);writePreviewEntityState(PREVIEW_TASK_KEY,state);dispatchEvent(new CustomEvent('fc-preview-task-action',{detail:draft}));dispatchEvent(new CustomEvent('fc-preview-tasks-changed'));return;}if(action.type==='memory.create'){const draft={id:`preview-memory-${Date.now()}`,memory_type:action.payload.memoryType||'preference',subject_type:action.payload.subjectType||'event',subject_id:null,title:action.payload.title||action.description,content:action.payload.content||{text:action.description},confidence:action.payload.confidence||'confirmed',source:'Copiloto · Preview',source_ref:null,status:'active',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};appendLocal(PREVIEW_MEMORY_KEY,draft,250);dispatchEvent(new CustomEvent('fc-preview-memory-action',{detail:draft}));return;}if(action.type==='music.create'){const draft={id:`copilot-music-${Date.now()}`,...action.payload,createdAt:new Date().toISOString(),source:'copilot-preview'};writePreviewEntityState(PREVIEW_MUSIC_KEY,upsertPreviewEntity(readPreviewEntityState<any>(PREVIEW_MUSIC_KEY),draft));dispatchEvent(new CustomEvent('fc-preview-music-action',{detail:draft}));dispatchEvent(new CustomEvent('fc-preview-music-changed'));return;}if(action.type==='timeline.create'){const draft={id:`copilot-timeline-${Date.now()}`,...action.payload,createdAt:new Date().toISOString(),source:'copilot-preview'};writePreviewEntityState(PREVIEW_TIMELINE_KEY,upsertPreviewEntity(readPreviewEntityState<any>(PREVIEW_TIMELINE_KEY),draft));dispatchEvent(new CustomEvent('fc-preview-timeline-action',{detail:draft}));dispatchEvent(new CustomEvent('fc-preview-timeline-changed'));}}
 async function resolveGuest(name:string){const supabase=createClient(),{data,error}=await supabase.from('wedding_guests').select('*').eq('guest_status','active');if(error)throw error;let guests=[...(data||[])];if(previewMode){const state=readGuestPreview(),map=new Map(guests.filter((g:any)=>!state.deleted.includes(g.id)).map((g:any)=>[g.id,g]));Object.values(state.overrides).forEach((g:any)=>{if(!state.deleted.includes(g.id))map.set(g.id,g);});guests=Array.from(map.values());}return uniqueMatch(guests,name,(g:any)=>[fullName(g)],'invitado');}
 async function resolveTable(tableNumber:number){const supabase=createClient(),{data,error}=await supabase.from('wedding_tables').select('*').eq('table_number',tableNumber).maybeSingle();if(error)throw error;let table=data;if(previewMode){const state=readTablePreview();if(table&&state.deleted.includes(table.id))table=null;if(table&&state.overrides[table.id])table=state.overrides[table.id];const created=state.created.find((t:any)=>Number(t.table_number)===tableNumber&&!state.deleted.includes(t.id));if(created)table=state.overrides[created.id]||created;}if(!table)throw new Error(`No existe la Mesa ${tableNumber}.`);return table;}
 async function resolveMusic(name:string){const r=await fetch('/api/music-source',{cache:'no-store'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No pude leer Música.');const items=previewMode?mergePreviewEntities(p.moments||[],readPreviewEntityState<any>(PREVIEW_MUSIC_KEY)):p.moments||[];return uniqueMatch(items,name,(item:any)=>[item.song,item.block].filter(Boolean),'ítem musical');}
 async function resolveTimeline(name:string){const r=await fetch('/api/timeline-source',{cache:'no-store'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No pude leer Cronograma.');const items=previewMode?mergePreviewEntities(p.items||[],readPreviewEntityState<any>(PREVIEW_TIMELINE_KEY)):p.items||[];return uniqueMatch(items,name,(item:any)=>[item.block].filter(Boolean),'bloque');}
 async function resolveTask(name:string){const r=await fetch('/api/tasks',{cache:'no-store'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No pude leer Tareas.');const items=previewMode?mergePreviewEntities(p.tasks||[],readPreviewEntityState<any>(PREVIEW_TASK_KEY)):p.tasks||[];return uniqueMatch(items,name,(item:any)=>[item.title].filter(Boolean),'tarea');}
 async function resolveBudget(name:string){const r=await fetch('/api/budget-source',{cache:'no-store'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No pude leer Presupuesto.');let items=p.items||[];if(previewMode){const state=readFinancePreview(),map=new Map(items.filter((i:any)=>!state.deleted.budget.includes(i.id)).map((i:any)=>[i.id,i]));Object.values(state.budget).forEach((i:any)=>{if(!state.deleted.budget.includes(i.id))map.set(i.id,i);});items=Array.from(map.values());}return uniqueMatch(items,name,(item:any)=>[item.item].filter(Boolean),'ítem de presupuesto');}
 async function resolveVendor(name:string){const supabase=createClient(),{data,error}=await supabase.from('vendors').select('*').order('name');if(error)throw error;let items=[...(data||[])];if(previewMode){const state=readFinancePreview(),map=new Map(items.filter((i:any)=>!state.deleted.vendors.includes(i.id)).map((i:any)=>[i.id,i]));Object.values(state.vendors).forEach((i:any)=>{if(!state.deleted.vendors.includes(i.id))map.set(i.id,i);});items=Array.from(map.values());}return uniqueMatch(items,name,(item:any)=>[item.name].filter(Boolean),'proveedor');}
 async function applyGuestUpdate(action:CopilotAction){const guest=await resolveGuest(action.payload.guestName),updates=action.payload.updates||{};if(previewMode){const state=readGuestPreview();state.overrides[guest.id]={...guest,...updates};state.deleted=state.deleted.filter(id=>id!==guest.id);writeGuestPreview(state);return;}const r=await fetch('/api/guests',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:guest.id,...updates})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible actualizar al invitado.');dispatchEvent(new CustomEvent('fc-data-guests-changed'));}
 async function applyGuestDelete(action:CopilotAction){const guest=await resolveGuest(action.payload.guestName);if(previewMode){const state=readGuestPreview();if(!state.deleted.includes(guest.id))state.deleted.push(guest.id);delete state.overrides[guest.id];writeGuestPreview(state);return;}const r=await fetch(`/api/guests?id=${encodeURIComponent(guest.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible eliminar al invitado.');dispatchEvent(new CustomEvent('fc-data-guests-changed'));}
 async function applyTableUpdate(action:CopilotAction){const table=await resolveTable(Number(action.payload.tableNumber)),patch=action.type==='table.rename'?{name:String(action.payload.name||'').trim()}:action.payload.patch||{};if(previewMode){const state=readTablePreview();state.overrides[table.id]={...table,...patch};writeTablePreview(state);return;}const r=await fetch('/api/tables',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:table.id,...patch})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible actualizar la mesa.');dispatchEvent(new CustomEvent('fc-data-tables-changed'));}
 async function applyTableCreate(action:CopilotAction){if(previewMode){const state=readTablePreview();if(state.created.some((t:any)=>Number(t.table_number)===Number(action.payload.table_number)))throw new Error(`Ya existe una Mesa ${action.payload.table_number} en el borrador.`);const id=`preview-table-${Date.now()}`,table={id,...action.payload,position_x:50,position_y:50,position_x_m:15,position_y_m:9,width:10,height:10,width_m:1.8,height_m:1.8,rotation:0,locked:false,notes:null};state.created.push(table);writeTablePreview(state);return;}const r=await fetch('/api/tables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action.payload)}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible crear la mesa.');dispatchEvent(new CustomEvent('fc-data-tables-changed'));}
 async function applyTableDelete(action:CopilotAction){const table=await resolveTable(Number(action.payload.tableNumber));if(previewMode){const state=readTablePreview();if(!state.deleted.includes(table.id))state.deleted.push(table.id);delete state.overrides[table.id];state.assignments=Object.fromEntries(Object.entries(state.assignments).map(([guestId,tableId])=>[guestId,tableId===table.id?null:tableId]));writeTablePreview(state);return;}const r=await fetch(`/api/tables?id=${encodeURIComponent(table.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible eliminar la mesa.');dispatchEvent(new CustomEvent('fc-data-tables-changed'));}
 async function applySeating(action:CopilotAction){const guest=await resolveGuest(action.payload.guestName);if(action.type==='seating.unassign'){if(previewMode){const state=readTablePreview();state.assignments[guest.id]=null;writeTablePreview(state);return;}const r=await fetch(`/api/seating?guest_id=${encodeURIComponent(guest.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible quitar la asignación.');dispatchEvent(new CustomEvent('fc-data-tables-changed'));return;}const table=await resolveTable(Number(action.payload.tableNumber));if(previewMode){const state=readTablePreview();state.assignments[guest.id]=table.id;writeTablePreview(state);return;}const r=await fetch('/api/seating',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guest_id:guest.id,table_id:table.id})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible asignar la mesa.');dispatchEvent(new CustomEvent('fc-data-tables-changed'));}
 async function applyMusic(action:CopilotAction){const item=await resolveMusic(action.payload.musicName);if(action.type==='music.update'){const next={...item,...(action.payload.updates||{})};if(previewMode){writePreviewEntityState(PREVIEW_MUSIC_KEY,upsertPreviewEntity(readPreviewEntityState<any>(PREVIEW_MUSIC_KEY),next));dispatchEvent(new CustomEvent('fc-preview-music-changed'));return;}const r=await fetch('/api/music-source',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,...action.payload.updates})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible actualizar Música.');dispatchEvent(new CustomEvent('fc-data-music-changed'));return;}if(previewMode){writePreviewEntityState(PREVIEW_MUSIC_KEY,removePreviewEntity(readPreviewEntityState<any>(PREVIEW_MUSIC_KEY),item.id));dispatchEvent(new CustomEvent('fc-preview-music-changed'));return;}const r=await fetch(`/api/music-source?id=${encodeURIComponent(item.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible eliminar el ítem musical.');dispatchEvent(new CustomEvent('fc-data-music-changed'));}
 async function applyTimeline(action:CopilotAction){const item=await resolveTimeline(action.payload.timelineName);if(action.type==='timeline.update'){const next={...item,...(action.payload.updates||{})};if(previewMode){writePreviewEntityState(PREVIEW_TIMELINE_KEY,upsertPreviewEntity(readPreviewEntityState<any>(PREVIEW_TIMELINE_KEY),next));dispatchEvent(new CustomEvent('fc-preview-timeline-changed'));return;}const r=await fetch('/api/timeline-source',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,...action.payload.updates})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible actualizar Cronograma.');dispatchEvent(new CustomEvent('fc-data-timeline-changed'));return;}if(previewMode){writePreviewEntityState(PREVIEW_TIMELINE_KEY,removePreviewEntity(readPreviewEntityState<any>(PREVIEW_TIMELINE_KEY),item.id));dispatchEvent(new CustomEvent('fc-preview-timeline-changed'));return;}const r=await fetch(`/api/timeline-source?id=${encodeURIComponent(item.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible eliminar el bloque.');dispatchEvent(new CustomEvent('fc-data-timeline-changed'));}
 async function applyTask(action:CopilotAction){const task=await resolveTask(action.payload.taskName);if(action.type==='task.update'){const next={...task,...(action.payload.updates||{}),updatedAt:new Date().toISOString()};if(previewMode){writePreviewEntityState(PREVIEW_TASK_KEY,upsertPreviewEntity(readPreviewEntityState<any>(PREVIEW_TASK_KEY),next));dispatchEvent(new CustomEvent('fc-preview-tasks-changed'));return;}const r=await fetch('/api/tasks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:task.id,...action.payload.updates})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible actualizar la tarea.');dispatchEvent(new CustomEvent('fc-data-tasks-changed'));return;}if(previewMode){writePreviewEntityState(PREVIEW_TASK_KEY,removePreviewEntity(readPreviewEntityState<any>(PREVIEW_TASK_KEY),task.id));dispatchEvent(new CustomEvent('fc-preview-tasks-changed'));return;}const r=await fetch(`/api/tasks?id=${encodeURIComponent(task.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible eliminar la tarea.');dispatchEvent(new CustomEvent('fc-data-tasks-changed'));}
 async function applyBudget(action:CopilotAction){if(action.type==='budget.create'){if(previewMode){const state=readFinancePreview(),id=`preview-budget-${Date.now()}`,item={id,rowNumber:Object.keys(state.budget).length+1,item:action.payload.item,projectedQuantity:action.payload.projectedQuantity??1,confirmedQuantity:action.payload.projectedQuantity??1,unitNet:null,projectedGross:action.payload.projectedGross??null,contractedAmount:null,category:action.payload.category||'General',responsible:'',status:action.payload.status||'Pendiente',notes:'Creado desde Copiloto',advance:0,currency:'CLP',dueDate:null,vendorId:null,sortOrder:Date.now()%1000000};state.budget[id]=item;writeFinancePreview(state);return;}const r=await fetch('/api/budget-source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action.payload)}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible crear el ítem de presupuesto.');dispatchEvent(new CustomEvent('fc-data-finance-changed'));return;}const item=await resolveBudget(action.payload.budgetName);if(action.type==='budget.update'){if(previewMode){const state=readFinancePreview();state.budget[item.id]={...item,...action.payload.updates};state.deleted.budget=state.deleted.budget.filter(id=>id!==item.id);writeFinancePreview(state);return;}const r=await fetch('/api/budget-source',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,...action.payload.updates})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible actualizar el presupuesto.');dispatchEvent(new CustomEvent('fc-data-finance-changed'));return;}if(previewMode){const state=readFinancePreview();if(!state.deleted.budget.includes(item.id))state.deleted.budget.push(item.id);delete state.budget[item.id];writeFinancePreview(state);return;}const r=await fetch(`/api/budget-source?id=${encodeURIComponent(item.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible eliminar el ítem.');dispatchEvent(new CustomEvent('fc-data-finance-changed'));}
 async function applyVendor(action:CopilotAction){if(action.type==='vendor.create'){if(previewMode){const state=readFinancePreview(),id=`preview-vendor-${Date.now()}`,vendor={id,name:action.payload.name,category:action.payload.category||'General',contact_name:null,phone:null,email:null,status:action.payload.status||'Evaluando',notes:'Creado desde Copiloto',production_status:action.payload.production_status||'Por coordinar'};state.vendors[id]=vendor;writeFinancePreview(state);return;}const r=await fetch('/api/vendors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action.payload)}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible crear el proveedor.');dispatchEvent(new CustomEvent('fc-data-finance-changed'));return;}const vendor=await resolveVendor(action.payload.vendorName);if(action.type==='vendor.update'){if(previewMode){const state=readFinancePreview();state.vendors[vendor.id]={...vendor,...action.payload.updates};state.deleted.vendors=state.deleted.vendors.filter(id=>id!==vendor.id);writeFinancePreview(state);return;}const r=await fetch('/api/vendors',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:vendor.id,...action.payload.updates})}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible actualizar el proveedor.');dispatchEvent(new CustomEvent('fc-data-finance-changed'));return;}if(previewMode){const state=readFinancePreview();if(!state.deleted.vendors.includes(vendor.id))state.deleted.vendors.push(vendor.id);delete state.vendors[vendor.id];writeFinancePreview(state);return;}const r=await fetch(`/api/vendors?id=${encodeURIComponent(vendor.id)}`,{method:'DELETE'}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible eliminar el proveedor.');dispatchEvent(new CustomEvent('fc-data-finance-changed'));}
 async function applyPayment(action:CopilotAction){const item=await resolveBudget(action.payload.budgetName),payload={budget_item_id:item.id,amount:Number(action.payload.amount),currency:action.payload.currency||'CLP',paid_at:new Date().toISOString().slice(0,10),payment_method:action.payload.payment_method||'Transferencia',status:action.payload.status||'Pagado',reference:null,notes:'Registrado desde Copiloto'};if(previewMode){const state=readFinancePreview(),id=`preview-payment-${Date.now()}`;state.payments[id]={id,...payload,event_budget_items:{id:item.id,concept:item.item,category:item.category}};writeFinancePreview(state);return;}const r=await fetch('/api/budget-payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible registrar el pago.');dispatchEvent(new CustomEvent('fc-data-finance-changed'));}
 async function applyAction(action:CopilotAction){updateActionState(action.id,'pending');try{if(action.type==='guest.update')await applyGuestUpdate(action);else if(action.type==='guest.delete')await applyGuestDelete(action);else if(action.type==='table.rename'||action.type==='table.update')await applyTableUpdate(action);else if(action.type==='table.create')await applyTableCreate(action);else if(action.type==='table.delete')await applyTableDelete(action);else if(action.type==='seating.assign'||action.type==='seating.unassign')await applySeating(action);else if(action.type==='music.update'||action.type==='music.delete')await applyMusic(action);else if(action.type==='timeline.update'||action.type==='timeline.delete')await applyTimeline(action);else if(action.type==='task.update'||action.type==='task.delete')await applyTask(action);else if(action.type.startsWith('budget.'))await applyBudget(action);else if(action.type.startsWith('vendor.'))await applyVendor(action);else if(action.type==='payment.create')await applyPayment(action);else if(previewMode){savePreviewStandard(action);}else{const endpoint=action.type==='guest.create'?'/api/guests':action.type==='music.create'?'/api/music-source':action.type==='timeline.create'?'/api/timeline-source':action.type==='memory.create'?'/api/memory':'/api/tasks';const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action.payload)}),p=await r.json().catch(()=>null);if(!r.ok||p?.ok===false)throw new Error(p?.message||p?.error||'No fue posible aplicar la acción.');dispatchEvent(new CustomEvent(action.type==='guest.create'?'fc-data-guests-changed':action.type==='music.create'?'fc-data-music-changed':action.type==='timeline.create'?'fc-data-timeline-changed':action.type==='memory.create'?'fc-data-memory-changed':'fc-data-tasks-changed'));}updateActionState(action.id,'applied',previewMode?`Confirmado como borrador local de Preview. Ya puedes revisarlo en ${destination(action.type)}.`:`Acción aplicada y auditada. Revisa el cambio en ${destination(action.type)}.`);}catch(e:any){updateActionState(action.id,'error',e?.message||'No fue posible aplicar la acción.');}}
 const quick=['Ayúdame a coordinar lo urgente','Revisar lista actualizada','¿Qué cambió desde mi última revisión?','¿Qué requiere atención ahora?','¿Qué falta para cerrar las mesas?','¿Qué decisiones faltan en música?'];
 return<><button type="button" className={styles.fab} onClick={toggle} aria-label={open?'Cerrar copiloto':'Abrir copiloto'}>{open?<X size={19}/>:<><Sparkles size={17}/><span>Copiloto</span></>}</button>{open&&<aside className={styles.panel} aria-label="Copiloto operacional"><header className={styles.header}><div className={styles.identity}><span><Bot size={18}/></span><div><strong>Copiloto operacional</strong><small>Datos conectados · CRUD con confirmación</small></div></div><button type="button" onClick={()=>setOpen(false)}><X size={17}/></button></header><div className={styles.context}><MessageCircle size={13}/><span>Contexto actual: <strong>{pageLabel}</strong></span><span>{previewMode?'Preview seguro':'Producción conectada'}</span></div><div className={styles.messages}>{messages.map((m,i)=><div key={`${m.role}-${i}`} className={`${styles.message} ${m.role==='user'?styles.user:styles.assistant}`}><span className={styles.messageText}>{m.text}</span>{m.action&&<div className={`${styles.actionCard} ${m.actionState==='applied'?styles.actionApplied:m.actionState==='discarded'?styles.actionDiscarded:m.actionState==='error'?styles.actionError:''}`}><span className={styles.actionKicker}>Acción propuesta</span><strong>{m.action.label}</strong><small>{m.action.description}</small>{m.actionState==='pending'&&<div><button type="button" onClick={()=>updateActionState(m.action!.id,'discarded')}>Descartar</button><button type="button" className={styles.confirmAction} onClick={()=>applyAction(m.action!)}><Check size={12}/>Confirmar</button></div>}{m.actionState==='applied'&&<span className={styles.actionState}><Check size={11}/>Confirmada</span>}{m.actionState==='discarded'&&<span className={styles.actionState}>Descartada</span>}{m.actionState==='error'&&<span className={styles.actionState}>No se pudo aplicar</span>}</div>}{m.meta&&<small className={styles.meta}>{m.meta}</small>}</div>)}{loading&&<div className={styles.loading}><Loader2 size={18} className="animate-spin"/><span>Consultando RSVP, mesas, finanzas, tareas y operación…</span></div>}</div><div className={styles.quick}>{quick.map(q=><button type="button" key={q} disabled={loading} onClick={()=>submit(q)}>{q}</button>)}</div><form className={styles.composer} onSubmit={e=>{e.preventDefault();submit();}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ej. Completa tarea Confirmar flores" disabled={loading}/><button type="submit" disabled={loading||!input.trim()}>{loading?<Loader2 size={15} className="animate-spin"/>:<Send size={15}/>}</button></form><footer className={styles.footer}><span>{previewMode?'Preview costo 0: CRUD como borradores persistentes; producción protegida.':'Consulta datos reales; toda mutación requiere confirmación.'}</span><Link href="/dashboard/planning" onClick={()=>setOpen(false)}>Abrir Planificación <ArrowRight size={12}/></Link></footer></aside>}</>;
}
