'use client';

import React,{useCallback,useEffect,useMemo,useState}from'react';
import{AlertTriangle,ArrowLeft,CheckCircle2,Edit3,Link2,Loader2,Plus,Save,Search,Trash2,Users,X}from'lucide-react';
import styles from'./RelationshipEditorDock.module.css';

type Member={id:string;guestId:string|null;personName:string;relation:string;rsvpStatus:string;sourceNote:string};
type Group={id:string;externalKey:string;name:string;linkType:string;confidence:'confirmed'|'probable';status:string;source:string;notes:string;members:Member[]};
type GroupForm={id:string;name:string;linkType:string;confidence:'confirmed'|'probable';notes:string;memberNames:string};
const KEY='fc-preview-relationships-v1',PANEL_ID='relationships';
const EMPTY:GroupForm={id:'',name:'',linkType:'Familia',confidence:'confirmed',notes:'',memberNames:''};
function readLocal():Group[]{try{const parsed=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function writeLocal(groups:Group[]){try{localStorage.setItem(KEY,JSON.stringify(groups));dispatchEvent(new CustomEvent('fc-relationships-changed'))}catch{}}

export default function RelationshipEditorDock(){
 const[open,setOpen]=useState(false),[groups,setGroups]=useState<Group[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[preview,setPreview]=useState(false),[search,setSearch]=useState(''),[editor,setEditor]=useState<GroupForm|null>(null),[expanded,setExpanded]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[memberInput,setMemberInput]=useState('');
 useEffect(()=>setPreview(location.hostname!=='gestion.felipeycami.cl'),[]);
 useEffect(()=>{const close=(event:Event)=>{if((event as CustomEvent<string>).detail!==PANEL_ID){setOpen(false);setEditor(null)}};addEventListener('fc-workspace-panel-open',close);addEventListener('fc-management-overlay-open',close);return()=>{removeEventListener('fc-workspace-panel-open',close);removeEventListener('fc-management-overlay-open',close)}},[]);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch('/api/relationships',{cache:'no-store'});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible leer relaciones.');let next=(payload.groups||[])as Group[];if(location.hostname!=='gestion.felipeycami.cl'){const local=readLocal();if(local.length)next=local}setGroups(next)}catch(err:any){setError(err?.message||'No fue posible leer relaciones.')}finally{setLoading(false)}},[]);
 useEffect(()=>{if(open)void load()},[open,load]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return groups.filter(group=>!q||`${group.name} ${group.linkType} ${group.members.map(m=>m.personName).join(' ')}`.toLowerCase().includes(q))},[groups,search]);
 const confirmed=groups.filter(g=>g.confidence==='confirmed').length;
 function openDock(){if(open){setOpen(false);setEditor(null);return}dispatchEvent(new CustomEvent('fc-workspace-panel-open',{detail:PANEL_ID}));dispatchEvent(new CustomEvent('fc-management-overlay-open',{detail:PANEL_ID}));setOpen(true)}
 function create(){setEditor({...EMPTY,id:`preview-rel-${Date.now()}`});setError(null);setNotice(null)}
 function edit(group:Group){setEditor({id:group.id,name:group.name,linkType:group.linkType,confidence:group.confidence,notes:group.notes,memberNames:''});setError(null);setNotice(null)}
 function localSave(form:GroupForm){setGroups(current=>{const found=current.find(g=>g.id===form.id);const supplied=form.memberNames.split(/[\n,]+/).map(v=>v.trim()).filter(Boolean);const members=found?.members||supplied.map((personName,index)=>({id:`preview-member-${Date.now()}-${index}`,guestId:null,personName,relation:'',rsvpStatus:'Confirmado',sourceNote:'Agregado manualmente en Preview'}));const group:Group={id:form.id,externalKey:found?.externalKey||'',name:form.name,linkType:form.linkType,confidence:form.confidence,status:'active',source:found?.source||'manual-preview',notes:form.notes,members};const next=found?current.map(g=>g.id===group.id?group:g):[...current,group];writeLocal(next);return next});setEditor(null);setNotice('Grupo guardado en el borrador persistente de Preview.')}
 async function save(){if(!editor?.name.trim()){setError('El nombre del grupo es obligatorio.');return}if(preview){localSave(editor);return}setSaving(true);setError(null);try{const isNew=editor.id.startsWith('preview-rel-');const members=editor.memberNames.split(/[\n,]+/).map(personName=>personName.trim()).filter(Boolean).map(personName=>({personName,rsvpStatus:'Confirmado'}));const response=await fetch('/api/relationships',{method:isNew?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(isNew?{name:editor.name,linkType:editor.linkType,confidence:editor.confidence,notes:editor.notes,members}:{id:editor.id,name:editor.name,linkType:editor.linkType,confidence:editor.confidence,notes:editor.notes})});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible guardar.');setEditor(null);setNotice('Relación actualizada y auditada.');await load()}catch(err:any){setError(err?.message||'No fue posible guardar.')}finally{setSaving(false)}}
 async function addMember(group:Group){const personName=memberInput.trim();if(!personName)return;if(preview){setGroups(current=>{const next=current.map(g=>g.id===group.id?{...g,members:[...g.members,{id:`preview-member-${Date.now()}`,guestId:null,personName,relation:'',rsvpStatus:'Confirmado',sourceNote:'Agregado manualmente en Preview'}]}:g);writeLocal(next);return next});setMemberInput('');return}const response=await fetch('/api/relationships',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'member',groupId:group.id,personName,rsvpStatus:'Confirmado'})});const payload=await response.json();if(!response.ok||!payload?.ok){setError(payload?.error||'No fue posible agregar persona.');return}setMemberInput('');await load()}
 async function removeMember(group:Group,member:Member){if(!confirm(`¿Quitar a ${member.personName} de ${group.name}?`))return;if(preview){setGroups(current=>{const next=current.map(g=>g.id===group.id?{...g,members:g.members.filter(m=>m.id!==member.id)}:g);writeLocal(next);return next});return}const response=await fetch(`/api/relationships?mode=member&id=${member.id}`,{method:'DELETE'});if(response.ok)await load();else setError('No fue posible quitar a la persona.')}
 async function removeGroup(group:Group){if(!confirm(`¿Eliminar el grupo “${group.name}”?`))return;if(preview){setGroups(current=>{const next=current.filter(g=>g.id!==group.id);writeLocal(next);return next});return}const response=await fetch(`/api/relationships?id=${group.id}`,{method:'DELETE'});const payload=await response.json();if(!response.ok||!payload?.ok){setError(payload?.error||'No fue posible eliminar.');return}await load()}

 return<><button type="button" className={styles.fab} onClick={openDock}>{open?<X size={17}/>:<><Link2 size={16}/><span>Relaciones</span></>}</button>{open&&<aside className={styles.panel} aria-label="Grupos para mesas">
  <header><div><span>Personas y vínculos</span><strong>{editor?'Editar grupo':'Grupos para mesas'}</strong><small>{editor?editor.name||'Nuevo grupo':`${groups.length} grupos · ${confirmed} conocidos · ${groups.length-confirmed} por validar`}</small></div><button onClick={()=>{setOpen(false);setEditor(null)}} aria-label="Cerrar"><X size={18}/></button></header>
  {editor?<>
    {error&&<div className={styles.error}><AlertTriangle size={15}/>{error}</div>}
    <div className={styles.editor}>
      <div className={styles.editorHead}><button onClick={()=>{setEditor(null);setError(null)}} aria-label="Volver a grupos" title="Volver a grupos"><ArrowLeft size={16}/></button><strong>{editor.id.startsWith('preview-rel-')?'Nuevo grupo':editor.name}</strong></div>
      <label><span>Nombre *</span><input value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})} placeholder="Ej. Familia Valverde"/></label>
      <div className={styles.grid}><label><span>Tipo</span><select value={editor.linkType} onChange={e=>setEditor({...editor,linkType:e.target.value})}><option>Pareja</option><option>Familia</option><option>Amistad</option><option>Grupo social</option><option>Por validar</option></select></label><label><span>Certeza</span><select value={editor.confidence} onChange={e=>setEditor({...editor,confidence:e.target.value as 'confirmed'|'probable'})}><option value="confirmed">Relación conocida</option><option value="probable">Por validar</option></select></label></div>
      {editor.id.startsWith('preview-rel-')&&<label><span>Personas iniciales</span><textarea rows={5} value={editor.memberNames} onChange={e=>setEditor({...editor,memberNames:e.target.value})} placeholder="Un nombre por línea o separados por coma"/></label>}
      <label><span>Notas</span><textarea rows={5} value={editor.notes} onChange={e=>setEditor({...editor,notes:e.target.value})} placeholder="Qué sabemos de este grupo, relación o criterio de mesa"/></label>
      <footer><button onClick={()=>{setEditor(null);setError(null)}}>Cancelar</button><button className={styles.primary} onClick={save} disabled={saving}>{saving?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>}Guardar grupo</button></footer>
    </div>
  </>:<>
    <div className={styles.info}><CheckCircle2 size={16}/><div><strong>Relaciones conocidas = reglas fuertes</strong><span>Los grupos “Por validar” sólo ayudan a la IA a sugerir. Nunca se transforman en parentescos confirmados sin tu revisión.</span></div></div>
    <div className={styles.toolbar}><label><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar grupo o persona…"/></label><button onClick={create}><Plus size={15}/>Nuevo grupo</button></div>
    {error&&<div className={styles.error}><AlertTriangle size={15}/>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
    {loading?<div className={styles.loading}><Loader2 size={20} className="animate-spin"/>Cargando relaciones…</div>:<div className={styles.list}>{filtered.map(group=><article key={group.id} className={group.confidence==='probable'?styles.probable:''}>
      <button className={styles.groupHead} onClick={()=>{setExpanded(expanded===group.id?null:group.id);setMemberInput('')}}><div><span>{group.confidence==='confirmed'?'Relación conocida':'Por validar'}</span><strong>{group.name}</strong><small>{group.linkType} · {group.members.length} personas</small></div><Users size={17}/></button>
      {expanded===group.id&&<div className={styles.details}><div className={styles.groupActions}><button onClick={()=>edit(group)}><Edit3 size={13}/>Editar grupo</button><button onClick={()=>removeGroup(group)}><Trash2 size={13}/>Eliminar grupo</button></div>{group.notes&&<p>{group.notes}</p>}<div className={styles.members}>{group.members.map(member=><div key={member.id}><span><strong>{member.personName}</strong><small>{member.relation||member.sourceNote||'Sin detalle'}</small></span><button onClick={()=>removeMember(group,member)} aria-label={`Quitar ${member.personName}`}><Trash2 size={12}/></button></div>)}</div><div className={styles.addMember}><input value={memberInput} onChange={e=>setMemberInput(e.target.value)} placeholder="Nombre exacto de la persona…" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void addMember(group)}}}/><button onClick={()=>addMember(group)}><Plus size={13}/>Agregar persona</button></div></div>}
    </article>)}{!filtered.length&&<div className={styles.empty}>No hay grupos en esta vista.</div>}</div>}
  </>}
 </aside>}</>;
}
