'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase-browser';
import { AlertTriangle, BrainCircuit, CheckCircle2, ChevronRight, Gauge, Loader2, RefreshCw, Save, SlidersHorizontal, Sparkles, Users, X } from 'lucide-react';
import styles from './SeatingIntelligenceDock.module.css';

type Guest = { id:string; first_name:string; last_name:string; group_name:string; family_side:string; family_branch?:string|null; guest_category:string; attendance_status:string; guest_status:string; virtual?:boolean; source?:string; };
type Table = { id:string; table_number:number; name:string; capacity:number; virtual?:boolean };
type Group = { groupId:string; groupName:string; linkType:string; confirmed:boolean; people:string[]; sourceNotes:string[] };
type ConfirmedPerson = { name:string; attendance?:string; source?:string; guestId?:string|null; masterGroup?:string; masterCategory?:string; masterOrigin?:string; masterObservations?:string; };
type Confirmed = { summary:{currentKnownAttending:number;currentKnownWithoutMaster:number;masterMetadataMatched?:number;masterMetadataMissing?:number}; people:ConfirmedPerson[]; incomingAttending:ConfirmedPerson[]; groups:Group[]; groupsSource?:string; masterGroupCounts?:Record<string,number>; dataQuality?:Array<{code:string;message:string}> };
type Unit = { id:string; guests:Guest[]; hard:boolean; probable:boolean; label:string; affinity:string; reason:string };
type ProposedTable = { table:Table; units:Unit[]; guests:Guest[]; affinity:string; reasons:string[] };
type ScenarioKey='cohesion'|'balanced'|'social';
type Rules={keepProbableTogether:boolean;allowFamilyMix:boolean;familyPriority:boolean};
type Score={total:number;hard:number;probable:number;capacity:number;cohesion:number;mix:number};
type Scenario={key:ScenarioKey;label:string;description:string;tables:ProposedTable[];score:Score;unplaced:number;virtualTables:number};

const DRAFT_KEY='fc-preview-seating-proposal-v2';
const RELATIONSHIPS_KEY='fc-preview-relationships-v1';
const GUEST_DRAFT_KEY='fc-preview-guests-v1';
const PANEL_ID='seating-intelligence';
function normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}
function fullName(guest:Guest){return `${guest.first_name} ${guest.last_name||''}`.trim();}
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value));}
function sideFromGroup(group:string){const value=normalize(group);if(value.includes('familia cami'))return'Camila';if(value.includes('familia felipe'))return'Felipe';return'';}
function affinityForGuest(guest:Guest){
  if(guest.family_branch&&normalize(guest.family_branch)!=='por clasificar')return guest.family_branch;
  const text=normalize(fullName(guest));const family=normalize(guest.family_side||'');const group=normalize(guest.group_name||'');
  if(family.includes('camila')||group.includes('familia cami')){if(/kalbhenn|muga/.test(text))return'Cami · Kalbhenn / Muga';if(/vargas|riffka/.test(text))return'Cami · Vargas / Riffka';return'Cami · familia por subdividir';}
  if(family.includes('felipe')||group.includes('familia felipe')){if(/garay|bustos/.test(text))return'Felipe · Garay / Bustos';if(/valverde|espinoza/.test(text))return'Felipe · Valverde / Espinoza';if(/cerda|escobedo/.test(text))return'Felipe · Cerda / Escobedo';return'Felipe · familia';}
  if(group.includes('amigos marcelo vargas'))return'Amigos · Marcelo Vargas';if(group.includes('familia marcelo vargas'))return'Familia · Marcelo Vargas';if(group.includes('t4ngible'))return'Amigos / socios · T4ngible';if(group.includes('trabajo'))return'Amigos / trabajo';return group&&group!=='sin clasificar'?guest.group_name:'Amigos / por clasificar';
}
function affinityForGuests(guests:Guest[]){const counts=new Map<string,number>();guests.forEach(g=>{const key=affinityForGuest(g);counts.set(key,(counts.get(key)||0)+1);});return Array.from(counts.entries()).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Amigos / por clasificar';}
const ORDER=['Cami · Mamá','Cami · Papá','Cami · Kalbhenn / Muga','Cami · Vargas / Riffka','Cami · familia por subdividir','Felipe · Mamá','Felipe · Papá','Felipe · Garay / Bustos','Felipe · Valverde / Espinoza','Felipe · Cerda / Escobedo','Felipe · familia','Familia · Marcelo Vargas','Amigos · Marcelo Vargas','Amigos / socios · T4ngible','Amigos / trabajo','Compartido · amigos','Compartido · trabajo','Amigos / por clasificar'];

function previewGroups():Group[]|null{
  try{
    const parsed=JSON.parse(window.localStorage.getItem(RELATIONSHIPS_KEY)||'[]');
    if(!Array.isArray(parsed)||!parsed.length)return null;
    return parsed.map((group:any)=>({groupId:group.externalKey||group.id,groupName:group.name,linkType:group.linkType,confirmed:group.confidence==='confirmed',people:(group.members||[]).map((member:any)=>member.personName).filter(Boolean),sourceNotes:Array.from(new Set((group.members||[]).map((member:any)=>member.sourceNote).filter(Boolean))) as string[]}));
  }catch{return null;}
}
function mergePreviewGuests(base:Guest[]):Guest[]{
  try{
    const state=JSON.parse(window.localStorage.getItem(GUEST_DRAFT_KEY)||'null');
    if(!state?.overrides)return base;
    const deleted=new Set<string>(Array.isArray(state.deleted)?state.deleted:[]);
    const map=new Map(base.filter(g=>!deleted.has(g.id)).map(g=>[g.id,g]));
    Object.values(state.overrides).forEach((raw:any)=>{const guest=raw as Guest;if(!guest?.id||deleted.has(guest.id))return;if(guest.guest_status==='active'&&guest.attendance_status==='attending')map.set(guest.id,guest);else map.delete(guest.id);});
    return Array.from(map.values()).sort((a,b)=>fullName(a).localeCompare(fullName(b),'es'));
  }catch{return base;}
}
function buildAllGuests(operational:Guest[],official:Confirmed|null){
  const map=new Map(operational.map(g=>[normalize(fullName(g)),g]));const result=[...operational];if(!official)return result;
  const known=[...(official.people||[]).filter(p=>p.attendance==='Asiste'),...(official.incomingAttending||[])];
  known.forEach((person,index)=>{const key=normalize(person.name);if(!key||map.has(key))return;const group=person.masterGroup||'Sin clasificar';const guest:Guest={id:`virtual-${key.replace(/ /g,'-')}-${index}`,first_name:person.name,last_name:'',group_name:group,family_side:sideFromGroup(group),family_branch:null,guest_category:person.masterCategory||'Adulto',attendance_status:'attending',guest_status:'active',virtual:true,source:person.source||'confirmed'};map.set(key,guest);result.push(guest);});
  return result;
}
function capacityTables(real:Table[],guestCount:number){const tables=real.slice().sort((a,b)=>a.table_number-b.table_number);let capacity=tables.reduce((s,t)=>s+t.capacity,0);let number=tables.reduce((max,t)=>Math.max(max,t.table_number),0)+1;while(capacity<guestCount){const size=Math.min(10,guestCount-capacity<6?8:10);tables.push({id:`virtual-table-${number}`,table_number:number,name:`Mesa ${number} · propuesta`,capacity:size,virtual:true});capacity+=size;number+=1;}return tables;}
function buildUnits(guests:Guest[],groups:Group[],rules:Rules){const byName=new Map(guests.map(g=>[normalize(fullName(g)),g]));const used=new Set<string>();const units:Unit[]=[];groups.filter(g=>g.confirmed).forEach(group=>{const members=group.people.map(n=>byName.get(normalize(n))).filter(Boolean) as Guest[];const available=members.filter(g=>!used.has(g.id));if(available.length<2)return;available.forEach(g=>used.add(g.id));units.push({id:`hard-${group.groupId}`,guests:available,hard:true,probable:false,label:group.groupName,affinity:affinityForGuests(available),reason:'Relación canónica conocida · regla fuerte'});});if(rules.keepProbableTogether)groups.filter(g=>!g.confirmed).forEach(group=>{const members=group.people.map(n=>byName.get(normalize(n))).filter(Boolean) as Guest[];const available=members.filter(g=>!used.has(g.id));if(available.length<2)return;available.forEach(g=>used.add(g.id));units.push({id:`soft-${group.groupId}`,guests:available,hard:false,probable:true,label:group.groupName,affinity:affinityForGuests(available),reason:'Vínculo por validar · preferencia blanda'});});guests.filter(g=>!used.has(g.id)).forEach(g=>units.push({id:`guest-${g.id}`,guests:[g],hard:false,probable:false,label:fullName(g),affinity:affinityForGuest(g),reason:g.virtual?'Afinidad desde BD_MAESTRA / confirmado; ficha operativa pendiente':g.family_branch?'Rama familiar explícita de la ficha':'Afinidad desde ficha operativa'}));return units;}
function emptyTables(tables:Table[]):ProposedTable[]{return tables.map(table=>({table,units:[],guests:[],affinity:'',reasons:[]}));}
function remaining(t:ProposedTable){return t.table.capacity-t.guests.length;}
function addUnit(t:ProposedTable,u:Unit){t.units.push(u);t.guests.push(...u.guests);if(!t.affinity)t.affinity=u.affinity;if(u.hard&&!t.reasons.includes('Respeta vínculos confirmados'))t.reasons.push('Respeta vínculos confirmados');if(u.probable&&!t.reasons.includes('Conserva vínculo probable'))t.reasons.push('Conserva vínculo probable');if(!t.reasons.includes(`Afinidad: ${u.affinity}`))t.reasons.push(`Afinidad: ${u.affinity}`);}
function orderUnits(units:Unit[],familyPriority:boolean){return units.slice().sort((a,b)=>{if(a.hard!==b.hard)return a.hard?-1:1;if(a.probable!==b.probable)return a.probable?-1:1;if(familyPriority){const ai=ORDER.indexOf(a.affinity),bi=ORDER.indexOf(b.affinity);if(ai!==bi)return(ai<0?999:ai)-(bi<0?999:bi);}return b.guests.length-a.guests.length;});}
function place(tables:Table[],units:Unit[],rules:Rules,mode:ScenarioKey){const result=emptyTables(tables);const unplaced:Unit[]=[];orderUnits(units,mode!=='social'&&rules.familyPriority).forEach(unit=>{const candidates=result.filter(t=>remaining(t)>=unit.guests.length);if(!candidates.length){unplaced.push(unit);return;}const ranked=candidates.map(t=>{const same=t.affinity===unit.affinity?1:0;const empty=t.guests.length===0?1:0;const load=t.guests.length/t.table.capacity;const diversity=new Set<string>(t.guests.map(affinityForGuest)).has(unit.affinity)?0:1;let score=0;if(mode==='cohesion')score=same*8+empty*2+load*2+((!rules.allowFamilyMix&&t.affinity&&t.affinity!==unit.affinity)?-12:0);else if(mode==='balanced')score=same*4+empty*2+load*3+((!rules.allowFamilyMix&&t.affinity&&t.affinity!==unit.affinity)?-8:0);else score=diversity*5+(unit.hard&&same?5:0)-load*2;return{t,score};}).sort((a,b)=>b.score-a.score||remaining(a.t)-remaining(b.t));addUnit(ranked[0].t,unit);});if(mode==='social')result.filter(t=>t.guests.length).forEach(t=>t.reasons.push('Escenario de mayor mezcla social'));return{tables:result,unplaced};}
function groupPreserved(group:Group,tables:ProposedTable[]){const names=new Set(group.people.map(normalize));const locations=tables.filter(t=>t.guests.some(g=>names.has(normalize(fullName(g))))).length;const present=tables.reduce((sum,t)=>sum+t.guests.filter(g=>names.has(normalize(fullName(g)))).length,0);return present<2||locations<=1;}
function scoreScenario(tables:ProposedTable[],groups:Group[],guests:Guest[],unplaced:number):Score{const hard=groups.filter(g=>g.confirmed),probable=groups.filter(g=>!g.confirmed);const hardOk=hard.filter(g=>groupPreserved(g,tables)).length,probOk=probable.filter(g=>groupPreserved(g,tables)).length;const capacity=tables.reduce((s,t)=>s+t.table.capacity,0),seated=tables.reduce((s,t)=>s+t.guests.length,0);const utilization=capacity?seated/capacity:0;const coh=tables.filter(t=>t.guests.length>1).map(t=>{const counts=new Map<string,number>();t.guests.forEach(g=>{const k=affinityForGuest(g);counts.set(k,(counts.get(k)||0)+1);});return Math.max(...Array.from(counts.values()))/t.guests.length;});const cohesion=coh.length?coh.reduce((a,b)=>a+b,0)/coh.length:1;const mixVals=tables.filter(t=>t.guests.length>1).map(t=>new Set(t.guests.map(affinityForGuest)).size);const mix=mixVals.length?clamp((mixVals.reduce((a,b)=>a+b,0)/mixVals.length-1)/3,0,1):0;const h=hard.length?hardOk/hard.length:1,p=probable.length?probOk/probable.length:1,penalty=guests.length?unplaced/guests.length:0;return{total:Math.round(clamp((h*.36+p*.12+utilization*.18+cohesion*.18+mix*.16-penalty*.5)*100,0,100)),hard:Math.round(h*100),probable:Math.round(p*100),capacity:Math.round(utilization*100),cohesion:Math.round(cohesion*100),mix:Math.round(mix*100)};}
function scenarios(realTables:Table[],guests:Guest[],groups:Group[],rules:Rules):Scenario[]{const tables=capacityTables(realTables,guests.length),units=buildUnits(guests,groups,rules);const defs:[ScenarioKey,string,string][]=[['cohesion','A · Cohesión familiar','Prioriza parejas, grupos conocidos y ramas familiares homogéneas.'],['balanced','B · Equilibrada','Mantiene vínculos y completa mesas sin aislar ramas innecesariamente.'],['social','C · Mezcla social','Conserva vínculos fuertes y aumenta la mezcla social.']];return defs.map(([key,label,description])=>{const built=place(tables,units,rules,key);const unplaced=built.unplaced.reduce((s,u)=>s+u.guests.length,0);return{key,label,description,tables:built.tables,unplaced,score:scoreScenario(built.tables,groups,guests,unplaced),virtualTables:built.tables.filter(t=>t.table.virtual).length};});}

export default function SeatingIntelligenceDock(){
  const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[operational,setOperational]=useState<Guest[]>([]),[realTables,setRealTables]=useState<Table[]>([]),[official,setOfficial]=useState<Confirmed|null>(null),[error,setError]=useState<string|null>(null),[expanded,setExpanded]=useState<number|null>(null),[active,setActive]=useState<ScenarioKey>('balanced'),[rulesOpen,setRulesOpen]=useState(false),[saved,setSaved]=useState(false);
  const[rules,setRules]=useState<Rules>({keepProbableTogether:true,allowFamilyMix:true,familyPriority:true});
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const supabase=createClient();const[g,t,o]=await Promise.all([supabase.from('wedding_guests').select('id, first_name, last_name, group_name, family_side, family_branch, guest_category, attendance_status, guest_status').eq('attendance_status','attending').eq('guest_status','active').order('first_name'),supabase.from('wedding_tables').select('id, table_number, name, capacity').order('table_number'),fetch('/api/confirmed-source',{cache:'no-store'})]);const op=await o.json();if(g.error||t.error)throw new Error(g.error?.message||t.error?.message||'No fue posible leer invitados/mesas.');if(!o.ok||!op?.ok)throw new Error(op?.error||'No fue posible leer relaciones.');let guestRows=(g.data||[]) as Guest[];if(window.location.hostname!=='gestion.felipeycami.cl'){guestRows=mergePreviewGuests(guestRows);const local=previewGroups();if(local?.length){op.groups=local;op.groupsSource='Preview · relaciones editables';}}setOperational(guestRows);setRealTables((t.data||[]) as Table[]);setOfficial(op);setSaved(false);}catch(err:any){setError(err?.message||'No fue posible construir la propuesta.');}finally{setLoading(false);}},[]);
  useEffect(()=>{const close=(event:Event)=>{if((event as CustomEvent<string>).detail!==PANEL_ID){setOpen(false);setExpanded(null)}};addEventListener('fc-workspace-panel-open',close);addEventListener('fc-management-overlay-open',close);return()=>{removeEventListener('fc-workspace-panel-open',close);removeEventListener('fc-management-overlay-open',close)}},[]);
  useEffect(()=>{if(open&&!official&&!loading)void load();},[open,official,loading,load]);
  useEffect(()=>{const changed=()=>{if(open)void load();else setOfficial(null);};window.addEventListener('fc-relationships-changed',changed);window.addEventListener('fc-preview-guests-changed',changed);return()=>{window.removeEventListener('fc-relationships-changed',changed);window.removeEventListener('fc-preview-guests-changed',changed);};},[open,load]);
  const allGuests=useMemo(()=>buildAllGuests(operational,official),[operational,official]);
  const generated=useMemo(()=>scenarios(realTables,allGuests,official?.groups||[],rules),[realTables,allGuests,official,rules]);
  const scenario=generated.find(s=>s.key===active)||generated[0];
  const hard=(official?.groups||[]).filter(g=>g.confirmed).length,probable=(official?.groups||[]).filter(g=>!g.confirmed).length,virtualGuests=allGuests.filter(g=>g.virtual).length,explicitBranches=allGuests.filter(g=>Boolean(g.family_branch)).length;
  function toggle(){setOpen(current=>{const next=!current;if(next){dispatchEvent(new CustomEvent('fc-workspace-panel-open',{detail:PANEL_ID}));dispatchEvent(new CustomEvent('fc-management-overlay-open',{detail:PANEL_ID}));}return next})}
  function saveDraft(){if(!scenario)return;try{window.localStorage.setItem(DRAFT_KEY,JSON.stringify({savedAt:new Date().toISOString(),scenario:scenario.key,rules,relationshipSource:official?.groupsSource||'Supabase',tables:scenario.tables.map(t=>({tableNumber:t.table.table_number,tableName:t.table.name,capacity:t.table.capacity,virtualTable:Boolean(t.table.virtual),affinity:t.affinity,people:t.guests.map(g=>({name:fullName(g),virtual:Boolean(g.virtual),source:g.source||'wedding_guests'})),reasons:t.reasons}))}));setSaved(true);window.dispatchEvent(new CustomEvent('fc-preview-seating-draft-changed'));}catch{setError('No fue posible guardar el borrador local.');}}

  return <><button type="button" className={styles.fab} onClick={toggle}>{open?<X size={17}/>:<><BrainCircuit size={16}/><span>IA de mesas</span></>}</button>{open&&<aside className={styles.panel}>
    <header><div><span>Seating Intelligence</span><strong>Distribución para todos los confirmados</strong><small>Confirmados + BD_MAESTRA + relaciones canónicas + ramas explícitas</small></div><button type="button" onClick={()=>setOpen(false)}><X size={16}/></button></header>
    {loading?<div className={styles.loading}><Loader2 className="animate-spin" size={20}/>Conciliando personas, grupos y capacidad…</div>:error?<div className={styles.error}><AlertTriangle size={15}/>{error}</div>:scenario&&<>
      <section className={styles.metrics}><div><strong>{allGuests.length}</strong><span>confirmados planificables</span></div><div><strong>{operational.length}</strong><span>con ficha operativa</span></div><div><strong>{virtualGuests}</strong><span>virtuales hasta conciliar</span></div></section>
      <div className={styles.policy}><CheckCircle2 size={14}/><div><strong>{hard} grupos conocidos = regla fuerte</strong><span>{probable} grupos por validar = preferencia · {explicitBranches} fichas con rama explícita · fuente: {official?.groupsSource||'relaciones canónicas'}. {scenario.virtualTables} mesa(s) adicionales son propuesta.</span></div></div>
      {(official?.summary.masterMetadataMissing||0)>0&&<div className={styles.error}><AlertTriangle size={14}/>{official?.summary.masterMetadataMissing} confirmado(s) no tienen coincidencia exacta en BD_MAESTRA; quedan en “por clasificar”.</div>}
      <div className={styles.scenarios}>{generated.map(s=><button type="button" key={s.key} className={active===s.key?styles.activeScenario:''} onClick={()=>{setActive(s.key);setExpanded(null);setSaved(false);}}><span>{s.label}</span><strong>{s.score.total}</strong><small>{s.description}</small></button>)}</div>
      <div className={styles.rulesButton}><button type="button" onClick={()=>setRulesOpen(v=>!v)}><SlidersHorizontal size={12}/>Reglas de propuesta</button><button type="button" onClick={saveDraft}><Save size={12}/>{saved?'Borrador guardado':'Usar como borrador'}</button></div>
      {rulesOpen&&<div className={styles.rules}><label><input type="checkbox" checked={rules.keepProbableTogether} onChange={e=>setRules(r=>({...r,keepProbableTogether:e.target.checked}))}/><span><strong>Intentar mantener vínculos probables</strong><small>No los convierte en relación confirmada.</small></span></label><label><input type="checkbox" checked={rules.familyPriority} onChange={e=>setRules(r=>({...r,familyPriority:e.target.checked}))}/><span><strong>Priorizar ramas familiares</strong><small>Usa primero family_branch explícito y después afinidades operativas sin inventar parentescos.</small></span></label><label><input type="checkbox" checked={rules.allowFamilyMix} onChange={e=>setRules(r=>({...r,allowFamilyMix:e.target.checked}))}/><span><strong>Permitir mezcla entre ramas</strong><small>Si se desactiva, evita mezclar mientras haya capacidad.</small></span></label></div>}
      <section className={styles.score}><div><Gauge size={14}/><strong>Score {scenario.score.total}/100</strong></div><span>Vínculos {scenario.score.hard}%</span><span>Probables {scenario.score.probable}%</span><span>Ocupación {scenario.score.capacity}%</span><span>Cohesión {scenario.score.cohesion}%</span><span>Mezcla {scenario.score.mix}%</span>{scenario.unplaced>0&&<span className={styles.scoreWarning}>{scenario.unplaced} sin ubicar</span>}</section>
      <div className={styles.toolbar}><button type="button" onClick={load}><RefreshCw size={12}/>Recalcular</button><span>{scenario.tables.reduce((s,t)=>s+t.guests.length,0)}/{allGuests.length} personas incluidas · {realTables.length} mesas reales + {scenario.virtualTables} propuestas</span></div>
      <div className={styles.tables}>{scenario.tables.map(item=>{const free=item.table.capacity-item.guests.length;return <article key={item.table.id} className={item.guests.length?styles.hasGuests:''}><button type="button" className={styles.tableHead} onClick={()=>setExpanded(expanded===item.table.table_number?null:item.table.table_number)}><div><span>Mesa {item.table.table_number}{item.table.virtual?' · propuesta':''}</span><strong>{item.affinity||'Disponible'}</strong><small>{item.guests.length}/{item.table.capacity} · {free} cupos libres</small></div><ChevronRight size={15}/></button>{expanded===item.table.table_number&&<div className={styles.details}><div className={styles.reasons}>{item.reasons.map(reason=><span key={reason}><Sparkles size={10}/>{reason}</span>)}</div><div className={styles.people}>{item.units.map(unit=><div key={unit.id} className={unit.hard?styles.hard:unit.probable?styles.probable:''}><strong>{unit.label}</strong><span>{unit.guests.map(g=>`${fullName(g)}${g.virtual?' · pendiente ficha':''}`).join(' · ')}</span><small>{unit.reason}</small></div>)}</div></div>}</article>})}</div>
      <footer><Users size={14}/><div><strong>Planifica ahora; persiste después de conciliar</strong><span>Las personas sin ficha pueden entrar al borrador, pero no a seating_assignments. Define ramas como “Cami · Mamá” o “Cami · Papá” en Invitados para afinar el algoritmo sin inventar parentescos.</span></div></footer>
    </>}
  </aside>}</>;
}
