'use client';

import React,{useEffect,useMemo,useState}from'react';
import{Check,Edit3,Loader2,Tag,X}from'lucide-react';
import{createClient}from'@/lib/supabase-browser';
import styles from'./TableNamingDock.module.css';

type TableItem={id:string;table_number:number;name:string;capacity:number;table_type:string;zone:string;position_x:number|string;position_y:number|string;width?:number|string;height?:number|string;rotation?:number|string;locked:boolean;notes:string|null;};
const SUGGESTIONS=['El Umbral','La Sobremesa','Los Viajes','El Primer Sí','Creciendo Juntos','Arboleda','Celebrar','Lo que Viene','La Risa','El Camino','Nuestra Gente','La Fiesta'];
const PREVIEW_KEY='fc-preview-tables-v2';

export default function TableNamingDock(){
 const[open,setOpen]=useState(false),[tables,setTables]=useState<TableItem[]>([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[saving,setSaving]=useState(false),[notice,setNotice]=useState('');
 const preview=typeof window!=='undefined'&&location.hostname!=='gestion.felipeycami.cl';
 useEffect(()=>{if(!open)return;(async()=>{const supabase=createClient(),{data}=await supabase.from('wedding_tables').select('*').order('table_number');const base=(data||[])as TableItem[];if(preview){try{const state=JSON.parse(localStorage.getItem(PREVIEW_KEY)||'null');if(state){const map=new Map(base.filter(t=>!state.deleted?.includes(t.id)).map(t=>[t.id,state.overrides?.[t.id]||t]));(state.created||[]).filter((t:TableItem)=>!state.deleted?.includes(t.id)).forEach((t:TableItem)=>map.set(t.id,state.overrides?.[t.id]||t));setTables(Array.from(map.values()).sort((a,b)=>a.table_number-b.table_number));return;}}catch{}}setTables(base);})();},[open,preview]);
 const selectedTable=useMemo(()=>tables.find(t=>t.id===selected)||null,[tables,selected]);
 useEffect(()=>{if(selectedTable)setName(selectedTable.name||`Mesa ${selectedTable.table_number}`);},[selectedTable]);
 function applySuggestion(value:string){setName(value);}
 async function save(){if(!selectedTable||!name.trim())return;setSaving(true);setNotice('');const next={...selectedTable,name:name.trim()};if(preview){try{const state=JSON.parse(localStorage.getItem(PREVIEW_KEY)||'{"overrides":{},"created":[],"deleted":[],"assignments":{}}');state.overrides=state.overrides||{};state.overrides[selectedTable.id]=next;localStorage.setItem(PREVIEW_KEY,JSON.stringify(state));setTables(cur=>cur.map(t=>t.id===next.id?next:t));setNotice('Nombre guardado en el borrador de Preview.');window.dispatchEvent(new CustomEvent('fc-preview-tables-changed'));}catch{setNotice('No pude guardar el borrador local.');}setSaving(false);return;}try{const r=await fetch('/api/tables',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selectedTable.id,name:name.trim()})}),p=await r.json();if(!r.ok||!p?.ok)throw new Error(p?.error||'No fue posible guardar.');setTables(cur=>cur.map(t=>t.id===p.table.id?p.table:t));setNotice('Nombre de mesa actualizado.');}catch(e:any){setNotice(e?.message||'No fue posible guardar.');}finally{setSaving(false);}}
 return<><button className={styles.fab} onClick={()=>setOpen(v=>!v)}>{open?<X size={16}/>:<><Tag size={15}/><span>Nombres de mesas</span></>}</button>{open&&<aside className={styles.panel}><header><div><span>Identidad de mesas</span><strong>Nombres con historia</strong><small>Número interno + nombre visible</small></div><button onClick={()=>setOpen(false)}><X size={16}/></button></header><div className={styles.body}><label><span>Mesa</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecciona una mesa…</option>{tables.map(t=><option key={t.id} value={t.id}>{String(t.table_number).padStart(2,'0')} · {t.name}</option>)}</select></label>{selectedTable&&<><label><span>Nombre visible</span><div className={styles.nameInput}><Edit3 size={13}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. El Umbral"/></div></label><div className={styles.suggestions}><span>Sugerencias</span><div>{SUGGESTIONS.map(s=><button key={s} className={name===s?styles.active:''} onClick={()=>applySuggestion(s)}>{s}</button>)}</div></div><div className={styles.preview}><span>{String(selectedTable.table_number).padStart(2,'0')}</span><strong>{name||'Nombre de mesa'}</strong></div><button className={styles.save} onClick={save} disabled={saving||!name.trim()}>{saving?<Loader2 size={13} className="animate-spin"/>:<Check size={13}/>}Guardar nombre</button>{notice&&<small className={styles.notice}>{notice}</small>}</>}</div><footer>La numeración sigue siendo operativa; el nombre es la identidad visible para seating, señalética y comunicaciones.</footer></aside>}</>;
}
