import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase-server';
import { getDatabaseWriteBlock } from '@/lib/environment-guard';

export const dynamic = 'force-dynamic';

async function auth(){
  const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();
  if(!user)return{ok:false as const,response:NextResponse.json({ok:false,error:'UNAUTHORIZED'},{status:401})};
  const {data:profile}=await supabase.from('admin_profiles').select('role, active').eq('id',user.id).single();
  if(!profile?.active)return{ok:false as const,response:NextResponse.json({ok:false,error:'FORBIDDEN'},{status:403})};
  return{ok:true as const,supabase,user,profile};
}
function toMoment(row:any,index=0){return{id:row.id,rowNumber:index+1,dateTime:row.planned_at||'',block:row.moment||'',owner:row.provider||'',duration:'',status:row.status||'Pendiente',dependencies:row.song?[row.song,row.artist].filter(Boolean).join(' · '):'',notes:row.cue||row.notes||'',song:row.song||'',artist:row.artist||'',version:row.version||'',url:row.url||'',provider:row.provider||'',cue:row.cue||'',priority:row.priority||'Normal',sortOrder:row.sort_order||0};}
function toBudget(row:any,index=0){return{id:row.id,rowNumber:index+1,item:row.concept||'',projectedQuantity:row.quantity??'',confirmedQuantity:row.quantity??'',unitNet:row.unit_net===null?null:Number(row.unit_net),vat:'',projectedGross:row.projected_gross===null?null:Number(row.projected_gross),category:row.category||'',responsible:row.responsible||'',status:row.status||'',notes:row.notes||'',advance:Number(row.paid_amount||0)};}

export async function GET(){
  try{const s=await auth();if(!s.ok)return s.response;const [musicResult,budgetResult]=await Promise.all([s.supabase.from('event_music_items').select('*').order('sort_order').order('planned_at'),s.supabase.from('event_budget_items').select('*').or('category.ilike.%música%,concept.ilike.%DJ%,concept.ilike.%Disociados%,concept.ilike.%sonido%,concept.ilike.%Violin%').order('sort_order')]);if(musicResult.error)throw musicResult.error;if(budgetResult.error)throw budgetResult.error;const moments=(musicResult.data||[]).map(toMoment);const budgetItems=(budgetResult.data||[]).map(toBudget);const confirmedMoments=moments.filter(i=>i.status.toLowerCase()==='confirmado').length;const confirmedBudget=budgetItems.filter(i=>i.status.toLowerCase()==='confirmado').length;const hasDetailedPlaylist=moments.some(i=>Boolean(i.song));return NextResponse.json({ok:true,sources:['Supabase · event_music_items','Supabase · event_budget_items'],canonical:true,moments,budgetItems,summary:{moments:moments.length,confirmedMoments,pendingMoments:moments.length-confirmedMoments,budgetItems:budgetItems.length,confirmedBudget,pendingBudget:budgetItems.length-confirmedBudget,budgetTotal:budgetItems.reduce((s,i)=>s+Number(i.projectedGross||0),0),hasDetailedPlaylist},fetchedAt:new Date().toISOString()});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible leer la operación musical.'},{status:500});}
}

export async function POST(request:Request){
  const block=getDatabaseWriteBlock();if(block)return NextResponse.json(block,{status:409});
  try{const s=await auth();if(!s.ok)return s.response;if(s.profile.role==='viewer')return NextResponse.json({ok:false,error:'VIEWER_MUTATION_DENIED'},{status:403});const body=await request.json();if(!String(body?.block||body?.moment||'').trim())return NextResponse.json({ok:false,error:'El momento musical es obligatorio.'},{status:400});const payload={moment:String(body.block||body.moment).trim(),planned_at:body.dateTime||body.plannedAt||null,song:body.song||null,artist:body.artist||null,version:body.version||null,url:body.url||null,provider:body.provider||body.owner||null,cue:body.cue||null,status:String(body.status||'Pendiente'),priority:String(body.priority||'Normal'),notes:body.notes||null,sort_order:Number(body.sortOrder||Date.now()%1000000)};const {data,error}=await s.supabase.from('event_music_items').insert(payload).select().single();if(error)throw error;await s.supabase.from('audit_log').insert({entity_type:'event_music_items',entity_id:data.id,action:'CREATE_MUSIC_ITEM',after_data:payload,actor:s.user.email,origin:'dashboard'});return NextResponse.json({ok:true,item:toMoment(data)});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible crear el momento musical.'},{status:500});}
}

export async function PATCH(request:Request){
  const block=getDatabaseWriteBlock();if(block)return NextResponse.json(block,{status:409});
  try{const s=await auth();if(!s.ok)return s.response;if(s.profile.role==='viewer')return NextResponse.json({ok:false,error:'VIEWER_MUTATION_DENIED'},{status:403});const body=await request.json();if(!body?.id)return NextResponse.json({ok:false,error:'ID_REQUIRED'},{status:400});const {data:before}=await s.supabase.from('event_music_items').select('*').eq('id',body.id).single();if(!before)return NextResponse.json({ok:false,error:'NOT_FOUND'},{status:404});const map:Record<string,string>={block:'moment',moment:'moment',dateTime:'planned_at',plannedAt:'planned_at',song:'song',artist:'artist',version:'version',url:'url',provider:'provider',owner:'provider',cue:'cue',status:'status',priority:'priority',notes:'notes',sortOrder:'sort_order'};const updates:Record<string,any>={};for(const[k,db]of Object.entries(map))if(k in body)updates[db]=body[k]===''?null:body[k];updates.updated_at=new Date().toISOString();const {data,error}=await s.supabase.from('event_music_items').update(updates).eq('id',body.id).select().single();if(error)throw error;await s.supabase.from('audit_log').insert({entity_type:'event_music_items',entity_id:body.id,action:'UPDATE_MUSIC_ITEM',before_data:before,after_data:updates,actor:s.user.email,origin:'dashboard'});return NextResponse.json({ok:true,item:toMoment(data)});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible actualizar el momento musical.'},{status:500});}
}

export async function DELETE(request:Request){
  const block=getDatabaseWriteBlock();if(block)return NextResponse.json(block,{status:409});
  try{const s=await auth();if(!s.ok)return s.response;if(s.profile.role!=='owner')return NextResponse.json({ok:false,error:'ONLY_OWNER_CAN_DELETE'},{status:403});const id=new URL(request.url).searchParams.get('id');if(!id)return NextResponse.json({ok:false,error:'ID_REQUIRED'},{status:400});const {data:before}=await s.supabase.from('event_music_items').select('*').eq('id',id).single();if(!before)return NextResponse.json({ok:false,error:'NOT_FOUND'},{status:404});const {error}=await s.supabase.from('event_music_items').delete().eq('id',id);if(error)throw error;await s.supabase.from('audit_log').insert({entity_type:'event_music_items',entity_id:id,action:'DELETE_MUSIC_ITEM',before_data:before,actor:s.user.email,origin:'dashboard'});return NextResponse.json({ok:true,deleted:true});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible eliminar el momento musical.'},{status:500});}
}
