'use client';

export const dynamic='force-dynamic';

import React,{useCallback,useEffect,useMemo,useState}from'react';
import Link from'next/link';
import DashboardLayout from '@/components/DashboardLayout';
import{createClient}from'@/lib/supabase-browser';
import{AlertTriangle,CheckCircle2,Edit3,GripVertical,Loader2,Plus,RefreshCw,Save,Search,Trash2,Users,X}from'lucide-react';
import'./tables-v3.css';

type TableItem={id:string;table_number:number;name:string;capacity:number;table_type:string;zone:string;position_x:number|string;position_y:number|string;width?:number|string;height?:number|string;rotation?:number|string;locked:boolean;notes:string|null;};
type Guest={id:string;first_name:string;last_name:string;group_name:string;family_side:string;attendance_status:string;dietary_type:string|null;dietary_detail:string|null;table_id:string|null;};
type Assignment={id:string;guest_id:string;table_id:string;seat_number:number|null;};
type Group={groupId:string;groupName:string;linkType:string;confirmed:boolean;people:string[];sourceNotes:string[];};
type Confirmed={summary:{currentKnownAttending:number;currentKnownWithoutMaster:number;currentKnownDietary:number};groups:Group[];groupsSource?:string;};
type PreviewState={overrides:Record<string,TableItem>;created:TableItem[];deleted:string[];assignments:Record<string,string|null>;};
type Notice={type:'success'|'error'|'info';text:string};
const KEY='fc-preview-tables-v2';const REL_KEY='fc-preview-relationships-v1';
const EMPTY_STATE:PreviewState={overrides:{},created:[],deleted:[],assignments:{}};
function num(value:unknown,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function fullName(g:Guest){return`${g.first_name} ${g.last_name||''}`.trim();}
function normalize(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');}
function readState():PreviewState{try{const parsed=JSON.parse(window.localStorage.getItem(KEY)||'null');return parsed?.assignments?parsed:structuredClone(EMPTY_STATE);}catch{return structuredClone(EMPTY_STATE);}}
function writeState(state:PreviewState){try{window.localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('fc-preview-tables-changed'));}catch{/* optional */}}
function previewGroups():Group[]|null{try{const parsed=JSON.parse(window.localStorage.getItem(REL_KEY)||'[]');if(!Array.isArray(parsed)||!parsed.length)return null;return parsed.map((group:any)=>({groupId:group.externalKey||group.id,groupName:group.name,linkType:group.linkType,confirmed:group.confidence==='confirmed',people:(group.members||[]).map((m:any)=>m.personName).filter(Boolean),sourceNotes:(group.members||[]).map((m:any)=>m.sourceNote).filter(Boolean)}));}catch{return null;}}
function mergeTables(base:TableItem[],state:PreviewState){const map=new Map(base.filter(t=>!state.deleted.includes(t.id)).map(t=>[t.id,state.overrides[t.id]||t]));state.created.filter(t=>!state.deleted.includes(t.id)).forEach(t=>map.set(t.id,state.overrides[t.id]||t));return Array.from(map.values()).sort((a,b)=>a.table_number-b.table_number);}
function mergeAssignments(base:Assignment[],state:PreviewState){const map=new Map(base.map(a=>[a.guest_id,a.table_id]));Object.entries(state.assignments).forEach(([guestId,tableId])=>{if(tableId)map.set(guestId,tableId);else map.delete(guestId);});return map;}

export default function TablesPage(){
 const[tables,setTables]=useState<TableItem[]>([]),[guests,setGuests]=useState<Guest[]>([]),[assignmentMap,setAssignmentMap]=useState<Map<string,string>>(new Map()),[confirmed,setConfirmed]=useState<Confirmed|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[saving,setSaving]=useState(false),[preview,setPreview]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState<'unassigned'|'assigned'|'linked'|'all'>('unassigned'),[selectedId,setSelectedId]=useState<string|null>(null),[draft,setDraft]=useState<Partial<TableItem>>({}),[notice,setNotice]=useState<Notice|null>(null),[dragGuest,setDragGuest]=useState<string|null>(null);
 useEffect(()=>setPreview(window.location.hostname!=='gestion.felipeycami.cl'),[]);
 const load=useCallback(async(manual=false)=>{if(manual)setRefreshing(true);setLoading(!manual);setNotice(null);try{const supabase=createClient();const[t,g,a,c]=await Promise.all([supabase.from('wedding_tables').select('*').order('table_number'),supabase.from('wedding_guests').select('id,first_name,last_name,group_name,family_side,attendance_status,dietary_type,dietary_detail,table_id').eq('guest_status','active').eq('attendance_status','attending').order('first_name'),supabase.from('seating_assignments').select('*'),fetch('/api/confirmed-source',{cache:'no-store'})]);const cp=await c.json();if(t.error||g.error||a.error)throw new Error(t.error?.message||g.error?.message||a.error?.message||'No fue posible cargar mesas.');if(!c.ok||!cp?.ok)throw new Error(cp?.error||'No fue posible cargar confirmados.');let tt=(t.data||[])as TableItem[],aa=(a.data||[])as Assignment[];if(window.location.hostname!=='gestion.felipeycami.cl'){const state=readState();tt=mergeTables(tt,state);const localGroups=previewGroups();if(localGroups?.length){cp.groups=localGroups;cp.groupsSource='Preview · relaciones editables';}setAssignmentMap(mergeAssignments(aa,state));}else setAssignmentMap(new Map(aa.map(item=>[item.guest_id,item.table_id])));setTables(tt);setGuests((g.data||[])as Guest[]);setConfirmed(cp);if(selectedId){const selected=tt.find(item=>item.id===selectedId);if(selected)setDraft({...selected});else setSelectedId(null);}}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible cargar Mesas.'});}finally{setLoading(false);setRefreshing(false);}},[selectedId]);
 useEffect(()=>{load();},[]);
 useEffect(()=>{const handler=()=>void load(true);window.addEventListener('fc-relationships-changed',handler);return()=>window.removeEventListener('fc-relationships-changed',handler);},[load]);
 const capacityByTable=useMemo(()=>{const map=new Map<string,Guest[]>();tables.forEach(t=>map.set(t.id,[]));guests.forEach(g=>{const tableId=assignmentMap.get(g.id)||g.table_id;if(tableId&&map.has(tableId))map.get(tableId)!.push(g);});return map;},[tables,guests,assignmentMap]);
 const assignedCount=useMemo(()=>guests.filter(g=>Boolean(assignmentMap.get(g.id)||g.table_id)).length,[guests,assignmentMap]);
 const groupsForGuest=useCallback((guest:Guest)=>(confirmed?.groups||[]).filter(group=>group.people.some(person=>normalize(person)===normalize(fullName(guest)))),[confirmed]);
 const hardGroupsSeparated=useMemo(()=>{const issues:string[]=[];(confirmed?.groups||[]).filter(group=>group.confirmed).forEach(group=>{const locations=new Set<string>();group.people.forEach(person=>{const guest=guests.find(item=>normalize(fullName(item))===normalize(person));if(!guest)return;const tableId=assignmentMap.get(guest.id)||guest.table_id;if(tableId)locations.add(tableId);});if(locations.size>1)issues.push(group.groupName);});return issues;},[confirmed,guests,assignmentMap]);
 const visibleGuests=useMemo(()=>{const q=normalize(search);return guests.filter(g=>{const tableId=assignmentMap.get(g.id)||g.table_id;const linked=groupsForGuest(g).length>0;if(filter==='unassigned'&&tableId)return false;if(filter==='assigned'&&!tableId)return false;if(filter==='linked'&&!linked)return false;if(q&&!normalize(`${fullName(g)} ${g.group_name} ${g.family_side}`).includes(q))return false;return true;});},[guests,assignmentMap,search,filter,groupsForGuest]);
 const selected=tables.find(t=>t.id===selectedId)||null;
 function selectTable(table:TableItem){setSelectedId(table.id);setDraft({...table});}
 function persistPreviewTable(table:TableItem,created=false){const state=readState();if(created){state.created=state.created.filter(item=>item.id!==table.id);state.created.push(table);}else state.overrides[table.id]=table;state.deleted=state.deleted.filter(id=>id!==table.id);writeState(state);}
 function persistPreviewAssignment(guestId:string,tableId:string|null){const state=readState();state.assignments[guestId]=tableId;writeState(state);}
 function updateLocalTable(table:TableItem,created=false){setTables(current=>{const exists=current.some(item=>item.id===table.id);return(exists?current.map(item=>item.id===table.id?table:item):[...current,table]).sort((a,b)=>a.table_number-b.table_number);});if(preview)persistPreviewTable(table,created);setDraft({...table});setSelectedId(table.id);}
 async function createTable(){const max=tables.reduce((m,t)=>Math.max(m,t.table_number),0);const index=tables.length;const table:TableItem={id:`preview-table-${Date.now()}`,table_number:max+1,name:`Mesa ${max+1}`,capacity:10,table_type:'round_guest',zone:'Principal',position_x:20+(index%4)*20,position_y:25+Math.floor(index/4)*24,width:10,height:10,rotation:0,locked:false,notes:null};if(preview){updateLocalTable(table,true);setNotice({type:'info',text:`Mesa ${max+1} creada como borrador persistente.`});return;}setSaving(true);try{const response=await fetch('/api/tables',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(table)});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible crear mesa.');await load(true);selectTable(payload.table);}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible crear mesa.'});}finally{setSaving(false);}}
 async function saveSelected(){if(!selected)return;const next:TableItem={...selected,...draft,table_number:Math.max(1,num(draft.table_number,selected.table_number)),capacity:Math.max(1,num(draft.capacity,selected.capacity)),name:String(draft.name||selected.name).trim()||selected.name,zone:String(draft.zone||selected.zone||'Principal'),table_type:String(draft.table_type||selected.table_type||'round_guest'),locked:Boolean(draft.locked)};const duplicate=tables.some(t=>t.id!==next.id&&t.table_number===next.table_number);if(duplicate){setNotice({type:'error',text:`Ya existe la Mesa ${next.table_number}.`});return;}const occupied=(capacityByTable.get(selected.id)||[]).length;if(next.capacity<occupied){setNotice({type:'error',text:`No puedes dejar capacidad ${next.capacity}: hay ${occupied} personas asignadas.`});return;}if(preview){updateLocalTable(next,selected.id.startsWith('preview-table-'));setNotice({type:'info',text:'Mesa guardada localmente y persistirá al recargar.'});return;}setSaving(true);try{const response=await fetch('/api/tables',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible guardar.');updateLocalTable(payload.table);setNotice({type:'success',text:'Mesa actualizada.'});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible guardar.'});}finally{setSaving(false);}}
 async function deleteSelected(){if(!selected)return;if((capacityByTable.get(selected.id)||[]).length){setNotice({type:'error',text:'Reasigna las personas antes de eliminar esta mesa.'});return;}if(!window.confirm(`¿Eliminar ${selected.name}?`))return;if(preview){const state=readState();state.deleted.push(selected.id);state.created=state.created.filter(t=>t.id!==selected.id);delete state.overrides[selected.id];writeState(state);setTables(current=>current.filter(t=>t.id!==selected.id));setSelectedId(null);setDraft({});setNotice({type:'info',text:'Mesa eliminada del borrador de Preview.'});return;}const response=await fetch(`/api/tables?id=${selected.id}`,{method:'DELETE'});const payload=await response.json();if(!response.ok||!payload?.ok){setNotice({type:'error',text:payload?.error||'No fue posible eliminar.'});return;}await load(true);setSelectedId(null);}
 async function assign(guestId:string,tableId:string,includeGroup=false){const guest=guests.find(g=>g.id===guestId),table=tables.find(t=>t.id===tableId);if(!guest||!table)return;let targets=[guest];const hard=groupsForGuest(guest).filter(group=>group.confirmed);if(includeGroup&&hard.length){const names=new Set(hard.flatMap(group=>group.people.map(normalize)));targets=guests.filter(g=>names.has(normalize(fullName(g))));}const currentOccupants=capacityByTable.get(tableId)||[];const alreadyAtTarget=targets.filter(g=>(assignmentMap.get(g.id)||g.table_id)===tableId).length;const newSeats=targets.length-alreadyAtTarget;if(currentOccupants.length+newSeats>table.capacity){setNotice({type:'error',text:`${table.name} no tiene cupo para ${targets.length} persona(s).`});return;}if(!includeGroup&&hard.length){const companions=hard.flatMap(group=>group.people).filter(person=>normalize(person)!==normalize(fullName(guest)));if(companions.length&&!window.confirm(`${fullName(guest)} pertenece a ${hard.map(g=>g.groupName).join(', ')}. ¿Mover sólo a esta persona?`))return;}
  if(preview){setAssignmentMap(current=>{const next=new Map(current);targets.forEach(g=>{next.set(g.id,tableId);persistPreviewAssignment(g.id,tableId);});return next;});setNotice({type:'info',text:`${targets.length} persona(s) asignadas a ${table.name} en el borrador persistente.`});return;}
  setSaving(true);try{for(const target of targets){const response=await fetch('/api/seating',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guest_id:target.id,table_id:tableId})});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||`No fue posible asignar a ${fullName(target)}.`);}await load(true);setNotice({type:'success',text:`${targets.length} persona(s) asignadas.`});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible asignar.'});}finally{setSaving(false);}}
 async function unassign(guestId:string){if(preview){setAssignmentMap(current=>{const next=new Map(current);next.delete(guestId);persistPreviewAssignment(guestId,null);return next;});return;}const response=await fetch(`/api/seating?guest_id=${guestId}`,{method:'DELETE'});const payload=await response.json();if(!response.ok||!payload?.ok){setNotice({type:'error',text:payload?.error||'No fue posible quitar de mesa.'});return;}await load(true);}
 function resetPreview(){if(!preview)return;window.localStorage.removeItem(KEY);void load(true);setNotice({type:'info',text:'Borrador de mesas restablecido a los datos canónicos.'});}
 const known=confirmed?.summary.currentKnownAttending||0,capacity=tables.reduce((sum,t)=>sum+t.capacity,0),operational=guests.length,missing=confirmed?.summary.currentKnownWithoutMaster||0;

 return<DashboardLayout><div className="tables-v3">
  <section className="tables-v3__hero"><div><span className="tables-v3__eyebrow">Personas y distribución</span><h1>Mesas</h1><p>Asigna invitados, conserva parejas y familias conocidas, administra capacidad y deja el detalle espacial para el editor de Salón.</p></div><div className="tables-v3__actions">{preview&&<span>Preview · borrador persistente</span>}<button onClick={()=>load(true)}><RefreshCw size={13} className={refreshing?'animate-spin':''}/>Actualizar</button><button className="is-primary" onClick={createTable}><Plus size={13}/>Nueva mesa</button></div></section>
  {notice&&<div className={`tables-v3__notice is-${notice.type}`}>{notice.type==='success'?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>}<span>{notice.text}</span></div>}
  <section className="tables-v3__metrics"><article><span>Confirmados conocidos</span><strong>{known}</strong><small>{missing} pendientes de ficha</small></article><article><span>Listos para distribuir</span><strong>{operational}</strong><small>fichas asistentes</small></article><article><span>Asignados</span><strong>{assignedCount}</strong><small>{operational-assignedCount} sin mesa</small></article><article className={capacity<known?'is-warning':''}><span>Capacidad</span><strong>{capacity}</strong><small>{capacity<known?`faltan ${known-capacity} cupos`:`+${capacity-known} cupos de holgura`}</small></article><article className={hardGroupsSeparated.length?'is-warning':''}><span>Grupos separados</span><strong>{hardGroupsSeparated.length}</strong><small>relaciones conocidas</small></article></section>
  {hardGroupsSeparated.length>0&&<div className="tables-v3__warning"><AlertTriangle size={15}/><span>Revisa grupos conocidos actualmente separados: {hardGroupsSeparated.join(' · ')}</span></div>}
  {loading?<div className="tables-v3__loading"><Loader2 size={20} className="animate-spin"/>Cargando invitados, mesas y relaciones…</div>:<section className="tables-v3__workspace">
   <aside className="tables-v3__bank"><header><div><span className="tables-v3__eyebrow">Banco operativo</span><h2>{operational-assignedCount} sin mesa</h2><small>{missing} confirmados adicionales se planifican en IA de mesas hasta tener ficha.</small></div></header><label className="tables-v3__search"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar persona, familia o grupo…"/></label><div className="tables-v3__filters">{(['unassigned','assigned','linked','all']as const).map(value=><button key={value} className={filter===value?'is-active':''} onClick={()=>setFilter(value)}>{value==='unassigned'?'Sin mesa':value==='assigned'?'Con mesa':value==='linked'?'Con vínculo':'Todos'}</button>)}</div><div className="tables-v3__guest-list">{visibleGuests.map(guest=>{const tableId=assignmentMap.get(guest.id)||guest.table_id;const links=groupsForGuest(guest);const hard=links.filter(g=>g.confirmed);return<article key={guest.id} draggable onDragStart={()=>setDragGuest(guest.id)} onDragEnd={()=>setDragGuest(null)}><span className="tables-v3__grip"><GripVertical size={13}/></span><span className="tables-v3__avatar">{guest.first_name[0]}</span><div className="tables-v3__guest-copy"><strong>{fullName(guest)}</strong><small>{guest.group_name||'Sin grupo'} · {guest.family_side||'Por clasificar'}</small>{links.length>0&&<span className={hard.length?'is-hard':'is-probable'}>{hard.length?'Vínculo conocido':'Vínculo por validar'} · {links[0].groupName}</span>}</div>{tableId?<button className="tables-v3__remove" onClick={()=>unassign(guest.id)}>Quitar</button>:<select defaultValue="" onChange={e=>{if(e.target.value)void assign(guest.id,e.target.value);e.currentTarget.value='';}}><option value="">Elegir mesa…</option>{tables.map(table=><option key={table.id} value={table.id}>{table.name} · {(capacityByTable.get(table.id)||[]).length}/{table.capacity}</option>)}</select>}</article>;})}</div></aside>
   <main className="tables-v3__distribution"><header><div><span className="tables-v3__eyebrow">Distribución</span><h2>{tables.length} mesas configuradas</h2></div><p>Arrastra una persona a una mesa o usa el selector. Si pertenece a un grupo conocido, puedes mover el grupo completo desde la tarjeta.</p></header><div className="tables-v3__grid">{tables.map(table=>{const occupants=capacityByTable.get(table.id)||[],selectedNow=selectedId===table.id;return<article key={table.id} className={`${selectedNow?'is-selected':''} ${occupants.length>=table.capacity?'is-full':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragGuest)void assign(dragGuest,table.id);setDragGuest(null);}}><button className="tables-v3__table-head" onClick={()=>selectTable(table)}><div><span>{table.zone||'Principal'}</span><strong>{table.name}</strong></div><b>{occupants.length}/{table.capacity}</b></button><div className="tables-v3__bar"><span style={{width:`${Math.min(100,(occupants.length/table.capacity)*100)}%`}}/></div><div className="tables-v3__occupants">{occupants.map(guest=><div key={guest.id}><span>{fullName(guest)}</span><button onClick={()=>unassign(guest.id)}><X size={10}/></button></div>)}{!occupants.length&&<small>Suelta invitados aquí</small>}</div>{occupants.some(g=>groupsForGuest(g).some(group=>group.confirmed))&&<div className="tables-v3__group-tools">{Array.from(new Map(occupants.flatMap(g=>groupsForGuest(g).filter(group=>group.confirmed)).map(group=>[group.groupId,group])).values()).map(group=>{const member=guests.find(g=>group.people.some(person=>normalize(person)===normalize(fullName(g))));return member?<button key={group.groupId} onClick={()=>assign(member.id,table.id,true)}><Users size={11}/>Mantener {group.groupName}</button>:null;})}</div>}<footer><span>{table.table_type==='rectangular_guest'?'Rectangular':'Redonda'} · {table.capacity} lugares</span><button onClick={()=>selectTable(table)}><Edit3 size={11}/>Editar</button></footer></article>;})}</div></main>
   <aside className="tables-v3__inspector">{selected?<><span className="tables-v3__eyebrow">Mesa seleccionada</span><h2>{selected.name}</h2><p>{(capacityByTable.get(selected.id)||[]).length} de {selected.capacity} lugares ocupados</p><label><span>Nombre</span><input value={String(draft.name??selected.name)} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="tables-v3__form-grid"><label><span>Número</span><input type="number" min="1" value={num(draft.table_number,selected.table_number)} onChange={e=>setDraft({...draft,table_number:Number(e.target.value)})}/></label><label><span>Capacidad</span><input type="number" min="1" max="30" value={num(draft.capacity,selected.capacity)} onChange={e=>setDraft({...draft,capacity:Number(e.target.value)})}/></label></div><label><span>Zona</span><input value={String(draft.zone??selected.zone)} onChange={e=>setDraft({...draft,zone:e.target.value})}/></label><label><span>Tipo</span><select value={String(draft.table_type??selected.table_type)} onChange={e=>setDraft({...draft,table_type:e.target.value})}><option value="round_guest">Redonda</option><option value="rectangular_guest">Rectangular</option></select></label><button className="tables-v3__save" onClick={saveSelected} disabled={saving}><Save size={13}/>{saving?'Guardando…':'Guardar cambios'}</button><button className="tables-v3__delete" onClick={deleteSelected}><Trash2 size={12}/>Eliminar mesa</button><Link href="/dashboard/venue">Continuar al salón →</Link></>:<div className="tables-v3__empty-inspector"><Users size={22}/><strong>Selecciona una mesa</strong><span>Podrás editar nombre, número, capacidad, zona y tipo.</span></div>}{preview&&<button className="tables-v3__reset" onClick={resetPreview}>Restablecer borrador</button>}</aside>
  </section>}
 </div></DashboardLayout>;
}
