import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase-server';
import { getDatabaseWriteBlock } from '@/lib/environment-guard';

export const dynamic='force-dynamic';

async function session(){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return{ok:false as const,response:NextResponse.json({ok:false,error:'UNAUTHORIZED'},{status:401})};const{data:profile}=await supabase.from('admin_profiles').select('role, active').eq('id',user.id).single();if(!profile?.active)return{ok:false as const,response:NextResponse.json({ok:false,error:'FORBIDDEN'},{status:403})};return{ok:true as const,supabase,user,profile};}
function validElements(value:any){if(!Array.isArray(value))return false;return value.every(item=>item&&typeof item.id==='string'&&typeof item.kind==='string'&&typeof item.label==='string'&&Number.isFinite(Number(item.x))&&Number.isFinite(Number(item.y))&&Number.isFinite(Number(item.width))&&Number.isFinite(Number(item.height))&&Number.isFinite(Number(item.rotation)));}

export async function GET(){try{const s=await session();if(!s.ok)return s.response;const{data,error}=await s.supabase.from('event_venue_layouts').select('*').eq('status','active').order('version',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return NextResponse.json({ok:true,layout:data||null,fetchedAt:new Date().toISOString()});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible leer el layout.'},{status:500});}}

export async function PATCH(request:Request){const block=getDatabaseWriteBlock();if(block)return NextResponse.json(block,{status:409});try{const s=await session();if(!s.ok)return s.response;if(s.profile.role==='viewer')return NextResponse.json({ok:false,error:'VIEWER_MUTATION_DENIED'},{status:403});const body=await request.json();if(!body?.id)return NextResponse.json({ok:false,error:'ID_REQUIRED'},{status:400});if('elements'in body&&!validElements(body.elements))return NextResponse.json({ok:false,error:'ELEMENTS_INVALID'},{status:400});const{data:before}=await s.supabase.from('event_venue_layouts').select('*').eq('id',body.id).single();if(!before)return NextResponse.json({ok:false,error:'NOT_FOUND'},{status:404});const updates:any={updated_at:new Date().toISOString()};for(const[key,db]of Object.entries({name:'name',venueName:'venue_name',status:'status',elements:'elements',referenceUrl:'reference_url',notes:'notes'}))if(key in body)updates[db]=body[key];if('version'in body)updates.version=Math.max(1,Number(body.version)||1);const{data,error}=await s.supabase.from('event_venue_layouts').update(updates).eq('id',body.id).select().single();if(error)throw error;await s.supabase.from('audit_log').insert({entity_type:'event_venue_layouts',entity_id:body.id,action:'UPDATE_VENUE_LAYOUT',before_data:before,after_data:updates,actor:s.user.email,origin:'dashboard'});return NextResponse.json({ok:true,layout:data});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible guardar el layout.'},{status:500});}}

export async function POST(request:Request){const block=getDatabaseWriteBlock();if(block)return NextResponse.json(block,{status:409});try{const s=await session();if(!s.ok)return s.response;if(s.profile.role==='viewer')return NextResponse.json({ok:false,error:'VIEWER_MUTATION_DENIED'},{status:403});const body=await request.json();if(!validElements(body?.elements))return NextResponse.json({ok:false,error:'ELEMENTS_INVALID'},{status:400});const{data:active}=await s.supabase.from('event_venue_layouts').select('id,version').eq('status','active').maybeSingle();if(active)await s.supabase.from('event_venue_layouts').update({status:'archived',updated_at:new Date().toISOString()}).eq('id',active.id);const{data,error}=await s.supabase.from('event_venue_layouts').insert({name:String(body.name||'Arboleda · Layout'),venue_name:String(body.venueName||'Arboleda Chicureo'),status:'active',version:Number(active?.version||0)+1,elements:body.elements,reference_url:body.referenceUrl||null,source:'Centro de Gestión',notes:body.notes||null}).select().single();if(error)throw error;await s.supabase.from('audit_log').insert({entity_type:'event_venue_layouts',entity_id:data.id,action:'CREATE_VENUE_LAYOUT',after_data:data,actor:s.user.email,origin:'dashboard'});return NextResponse.json({ok:true,layout:data});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||'No fue posible crear el layout.'},{status:500});}}
