'use client';

export const dynamic = 'force-dynamic';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import DashboardLayout from '@/components/DashboardLayout';
import { createClient } from '@/lib/supabase-browser';
import { AlertCircle, Building2, CheckCircle2, DollarSign, Edit3, Loader2, Plus, RefreshCw, Save, Trash2, WalletCards, X } from 'lucide-react';
import './finance-v2.css';
import './finance-edit.css';

interface Vendor { id:string; name:string; category:string; contact_name:string|null; phone:string|null; email:string|null; status:string; notes:string|null; }
interface Expense { id:string; vendor_id:string|null; concept:string; category:string; currency:string; total_amount:number|null; payment_status:string; due_date:string|null; responsible:string|null; notes:string|null; }
interface Payment { id:string; expense_id:string; amount:number|null; currency:string; payment_date:string|null; payment_type:string|null; status:string; reference:string|null; notes:string|null; }
interface BudgetItem { rowNumber:number; item:string; projectedQuantity:string; confirmedQuantity:string; unitNet:number|null; vat:string; projectedGross:number|null; category:string; responsible:string; status:string; notes:string; advance:number|null; }
interface BudgetSource { ok:boolean; source:string; mode?:'production'|'staging'; items:BudgetItem[]; summary:{paidOrPrepaid:number|null;remaining:number|null;totalBudget:number|null}; fetchedAt:string; error?:string; }
type Tab='budget'|'vendors'|'payments';
type Drawer='budget'|'vendor'|'payment'|null;
type Notice={type:'success'|'error'|'info';text:string};

const EMPTY_BUDGET:BudgetItem={rowNumber:0,item:'',projectedQuantity:'1',confirmedQuantity:'',unitNet:null,vat:'0.19',projectedGross:null,category:'',responsible:'',status:'Pendiente',notes:'',advance:null};
const EMPTY_VENDOR:Vendor={id:'',name:'',category:'',contact_name:'',phone:'',email:'',status:'Evaluando',notes:''};
const EMPTY_PAYMENT:Payment={id:'',expense_id:'',amount:null,currency:'CLP',payment_date:new Date().toISOString().slice(0,10),payment_type:'Transferencia',status:'Pagado',reference:'',notes:''};

function money(value:number|null|undefined){if(value===null||value===undefined)return 'Por confirmar';return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value);}
function formatDate(value:string|null){if(!value)return 'Por definir';try{return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(new Date(`${value}T12:00:00`));}catch{return value;}}
function num(value:string){const parsed=Number(value);return Number.isFinite(parsed)?parsed:null;}

export default function FinancePage(){
  const [vendors,setVendors]=useState<Vendor[]>([]);
  const [expenses,setExpenses]=useState<Expense[]>([]);
  const [payments,setPayments]=useState<Payment[]>([]);
  const [budget,setBudget]=useState<BudgetSource|null>(null);
  const [loading,setLoading]=useState(true);
  const [refreshing,setRefreshing]=useState(false);
  const [saving,setSaving]=useState(false);
  const [tab,setTab]=useState<Tab>('budget');
  const [drawer,setDrawer]=useState<Drawer>(null);
  const [creating,setCreating]=useState(false);
  const [notice,setNotice]=useState<Notice|null>(null);
  const [previewMode,setPreviewMode]=useState(false);
  const [budgetForm,setBudgetForm]=useState<BudgetItem>(EMPTY_BUDGET);
  const [vendorForm,setVendorForm]=useState<Vendor>(EMPTY_VENDOR);
  const [paymentForm,setPaymentForm]=useState<Payment>(EMPTY_PAYMENT);

  useEffect(()=>setPreviewMode(window.location.hostname!=='gestion.felipeycami.cl'),[]);

  const loadData=useCallback(async(manual=false)=>{
    if(manual)setRefreshing(true);setLoading(!manual);setNotice(null);
    try{
      const supabase=createClient();
      const [v,e,p,b]=await Promise.all([
        supabase.from('vendors').select('*').order('name'),
        supabase.from('expenses').select('*').order('created_at',{ascending:false}),
        supabase.from('expense_payments').select('*').order('created_at',{ascending:false}),
        fetch('/api/budget-source',{cache:'no-store'}),
      ]);
      const errors=[v.error,e.error,p.error].filter(Boolean);if(errors.length)throw new Error(errors.map((item)=>item?.message).join(' · '));
      const bp=await b.json().catch(()=>null);
      setVendors((v.data||[]) as Vendor[]);setExpenses((e.data||[]) as Expense[]);setPayments((p.data||[]) as Payment[]);
      if(b.ok&&bp?.ok)setBudget(bp as BudgetSource);else throw new Error(bp?.error||'No fue posible leer el presupuesto operativo.');
    }catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible cargar finanzas.'});}
    finally{setLoading(false);setRefreshing(false);}
  },[]);
  useEffect(()=>{loadData();},[loadData]);

  const paidSupabase=useMemo(()=>payments.filter((p)=>p.currency==='CLP'&&p.status==='Pagado').reduce((sum,p)=>sum+Number(p.amount||0),0),[payments]);
  const contractedVendors=vendors.filter((v)=>v.status==='Contratado').length;
  const budgetMissing=(budget?.items||[]).filter((item)=>item.projectedGross===null||(item.projectedGross===0&&item.unitNet===null)).length;

  function openBudget(item?:BudgetItem){setCreating(!item);setBudgetForm(item?{...item}:{...EMPTY_BUDGET});setDrawer('budget');}
  function openVendor(item?:Vendor){setCreating(!item);setVendorForm(item?{...item}:{...EMPTY_VENDOR});setDrawer('vendor');}
  function openPayment(item?:Payment){setCreating(!item);setPaymentForm(item?{...item}:{...EMPTY_PAYMENT});setDrawer('payment');}
  function closeDrawer(){if(!saving)setDrawer(null);}

  async function saveBudget(event:React.FormEvent){event.preventDefault();if(!budgetForm.item.trim())return;setSaving(true);try{
    const response=await fetch('/api/budget-source',{method:creating?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(budgetForm)});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible guardar el presupuesto.');setDrawer(null);await loadData();setNotice({type:'success',text:`${creating?'Ítem creado':'Ítem actualizado'} en ${payload.mode==='staging'?'STAGING':'el presupuesto operativo'}.`});
  }catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible guardar el presupuesto.'});}finally{setSaving(false);}}

  async function deleteBudget(){if(creating||!budgetForm.rowNumber)return;if(!window.confirm(`¿Eliminar “${budgetForm.item}” del presupuesto?`))return;setSaving(true);try{const response=await fetch(`/api/budget-source?rowNumber=${budgetForm.rowNumber}`,{method:'DELETE'});const payload=await response.json();if(!response.ok||!payload?.ok)throw new Error(payload?.error||'No fue posible eliminar el ítem.');setDrawer(null);await loadData();setNotice({type:'success',text:`Ítem eliminado de ${payload.mode==='staging'?'STAGING':'la fuente operativa'}.`});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible eliminar el ítem.'});}finally{setSaving(false);}}

  async function saveVendor(event:React.FormEvent){event.preventDefault();if(!vendorForm.name.trim())return;const draft={...vendorForm,id:vendorForm.id||`preview-vendor-${Date.now()}`};if(previewMode){setVendors((current)=>creating?[...current,draft]:current.map((item)=>item.id===draft.id?draft:item));setDrawer(null);setNotice({type:'info',text:`Proveedor ${creating?'creado':'actualizado'} localmente. La persistencia Supabase de Preview se habilitará al crear staging.`});return;}setSaving(true);try{const response=await fetch('/api/vendors',{method:creating?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(vendorForm)});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||'No fue posible guardar proveedor.');setDrawer(null);await loadData();setNotice({type:'success',text:`Proveedor ${creating?'creado':'actualizado'} correctamente.`});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible guardar proveedor.'});}finally{setSaving(false);}}

  async function deleteVendor(){if(creating||!vendorForm.id)return;if(!window.confirm(`¿Eliminar ${vendorForm.name}? Los gastos existentes conservarán su historial sin proveedor asociado.`))return;if(previewMode){setVendors((current)=>current.filter((item)=>item.id!==vendorForm.id));setDrawer(null);setNotice({type:'info',text:'Proveedor eliminado localmente en Preview. Producción permanece intacta.'});return;}setSaving(true);try{const response=await fetch(`/api/vendors?id=${vendorForm.id}`,{method:'DELETE'});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||'No fue posible eliminar proveedor.');setDrawer(null);await loadData();setNotice({type:'success',text:'Proveedor eliminado.'});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible eliminar proveedor.'});}finally{setSaving(false);}}

  async function savePayment(event:React.FormEvent){event.preventDefault();if(!paymentForm.expense_id||!paymentForm.amount)return;const draft={...paymentForm,id:paymentForm.id||`preview-payment-${Date.now()}`,currency:'CLP'};if(previewMode){setPayments((current)=>creating?[draft,...current]:current.map((item)=>item.id===draft.id?draft:item));setDrawer(null);setNotice({type:'info',text:`Pago ${creating?'registrado':'actualizado'} localmente. La persistencia Supabase de Preview se habilitará con staging.`});return;}setSaving(true);try{const response=await fetch('/api/payments',{method:creating?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const payload=await response.json().catch(()=>({ok:response.ok}));if(!response.ok||payload.ok===false)throw new Error(payload.error||'No fue posible guardar pago.');setDrawer(null);await loadData();setNotice({type:'success',text:`Pago ${creating?'registrado':'actualizado'} correctamente.`});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible guardar pago.'});}finally{setSaving(false);}}

  async function deletePayment(){if(creating||!paymentForm.id)return;if(!window.confirm('¿Eliminar este pago?'))return;if(previewMode){setPayments((current)=>current.filter((item)=>item.id!==paymentForm.id));setDrawer(null);setNotice({type:'info',text:'Pago eliminado localmente en Preview.'});return;}setSaving(true);try{const response=await fetch(`/api/payments?id=${paymentForm.id}`,{method:'DELETE'});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||'No fue posible eliminar pago.');setDrawer(null);await loadData();setNotice({type:'success',text:'Pago eliminado.'});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible eliminar pago.'});}finally{setSaving(false);}}

  return <DashboardLayout><div className="finance-v2">
    <section className="finance-v2__hero"><div><span className="finance-v2__eyebrow">Organización financiera</span><h1>Presupuesto y proveedores</h1><p>Edita el presupuesto desde el Centro de Gestión y administra proveedores y pagos sin depender de la hoja manualmente.</p></div><div className="finance-v2__actions">{previewMode&&<span className="finance-v2__preview">Preview · Sheets persistente en STAGING</span>}<button type="button" onClick={()=>loadData(true)}><RefreshCw size={14} className={refreshing?'animate-spin':''}/>{refreshing?'Actualizando…':'Actualizar'}</button></div></section>
    {notice&&<div className={`finance-v2__notice finance-v2__notice--${notice.type}`}>{notice.type==='success'?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>}<span>{notice.text}</span></div>}
    <section className="finance-v2__source"><div><span>Fuente de presupuesto</span><strong>{budget?.source||'Cargando…'}</strong><small>{budget?.mode==='staging'?'editable en copia persistente de prueba':'fuente operativa'}</small></div><div><span>Presupuesto total</span><strong>{money(budget?.summary.totalBudget)}</strong><small>recalculado desde ítems</small></div><div><span>Pagado / prepagado</span><strong>{money(budget?.summary.paidOrPrepaid)}</strong><small>resumen vigente</small></div><div><span>Faltante</span><strong>{money(budget?.summary.remaining)}</strong><small>saldo calculado</small></div></section>
    <section className="finance-v2__metrics"><article><span>Ítems presupuestados</span><strong>{budget?.items.length||0}</strong><small>{budgetMissing} con monto por completar</small></article><article><span>Proveedores</span><strong>{vendors.length}</strong><small>{contractedVendors} contratados</small></article><article><span>Pagos estructurados</span><strong>{payments.length}</strong><small>{money(paidSupabase)} registrados</small></article><article><span>Registros de gasto</span><strong>{expenses.length}</strong><small>base estructurada existente</small></article></section>

    <section className="finance-v2__toolbar"><div className="finance-v2__tabs"><button className={tab==='budget'?'is-active':''} onClick={()=>setTab('budget')}><WalletCards size={14}/>Presupuesto</button><button className={tab==='vendors'?'is-active':''} onClick={()=>setTab('vendors')}><Building2 size={14}/>Proveedores</button><button className={tab==='payments'?'is-active':''} onClick={()=>setTab('payments')}><DollarSign size={14}/>Pagos</button></div><div className="finance-v2__toolbar-actions">{tab==='budget'&&<button onClick={()=>openBudget()}><Plus size={13}/>Nuevo ítem</button>}{tab==='vendors'&&<button onClick={()=>openVendor()}><Plus size={13}/>Nuevo proveedor</button>}{tab==='payments'&&<button onClick={()=>openPayment()}><Plus size={13}/>Registrar pago</button>}</div></section>

    {loading?<div className="finance-v2__loading"><Loader2 className="animate-spin" size={20}/>Cargando fuentes financieras…</div>:tab==='budget'?<section className="finance-v2__budget"><div className="finance-v2__budget-head"><div><span>Ítem</span><span>Categoría</span><span>Responsable</span><span>Estado</span><span>Total proyectado</span><span/></div></div><div className="finance-v2__budget-list">{(budget?.items||[]).map((item)=><article key={item.rowNumber} onClick={()=>openBudget(item)} role="button" tabIndex={0}><div className="finance-v2__budget-name"><strong>{item.item}</strong><small>{item.notes||`${item.confirmedQuantity||item.projectedQuantity||'—'} unidades`}</small></div><span>{item.category||'—'}</span><span>{item.responsible||'—'}</span><span className="finance-v2__status">{item.status||'Sin estado'}</span><strong className={item.projectedGross===null?'is-missing':''}>{money(item.projectedGross)}</strong><button type="button" onClick={(e)=>{e.stopPropagation();openBudget(item);}} aria-label={`Editar ${item.item}`}><Edit3 size={13}/></button></article>)}</div></section>:tab==='vendors'?<section className="finance-v2__vendor-grid">{vendors.map((vendor)=><article key={vendor.id} onClick={()=>openVendor(vendor)} role="button" tabIndex={0}><div className="finance-v2__vendor-top"><span><Building2 size={16}/></span><small>{vendor.status}</small></div><h2>{vendor.name}</h2><p>{vendor.category||'Sin categoría'}</p><dl><div><dt>Contacto</dt><dd>{vendor.contact_name||'Por completar'}</dd></div><div><dt>Teléfono</dt><dd>{vendor.phone||'Por completar'}</dd></div><div><dt>Email</dt><dd>{vendor.email||'Por completar'}</dd></div></dl>{vendor.notes&&<footer>{vendor.notes}</footer>}<button className="finance-v2__card-edit" type="button" onClick={(e)=>{e.stopPropagation();openVendor(vendor);}}><Edit3 size={12}/>Editar</button></article>)}</section>:<section className="finance-v2__payments">{payments.map((payment)=>{const expense=expenses.find((item)=>item.id===payment.expense_id);return <article key={payment.id} onClick={()=>openPayment(payment)} role="button" tabIndex={0}><span className="finance-v2__payment-icon"><DollarSign size={15}/></span><div><strong>{expense?.concept||payment.payment_type||'Pago'}</strong><small>{formatDate(payment.payment_date)} · {payment.payment_type||'Sin medio'}</small></div><strong>{money(payment.amount)}</strong><span className="finance-v2__status">{payment.status}</span><button type="button" onClick={(e)=>{e.stopPropagation();openPayment(payment);}}><Edit3 size={12}/></button></article>})}{!payments.length&&<div className="finance-v2__empty">Aún no hay pagos estructurados.</div>}</section>}

    {drawer&&<><button type="button" className="finance-v2__backdrop" aria-label="Cerrar" onClick={closeDrawer}/><aside className="finance-v2__drawer"><header><div><span className="finance-v2__eyebrow">{drawer==='budget'?'Presupuesto':drawer==='vendor'?'Proveedores':'Pagos'}</span><h2>{creating?drawer==='budget'?'Nuevo ítem':drawer==='vendor'?'Nuevo proveedor':'Registrar pago':drawer==='budget'?budgetForm.item:drawer==='vendor'?vendorForm.name:'Editar pago'}</h2></div><button type="button" onClick={closeDrawer} disabled={saving}><X size={18}/></button></header>
      {drawer==='budget'?<form onSubmit={saveBudget}><label><span>Ítem *</span><input value={budgetForm.item} onChange={(e)=>setBudgetForm({...budgetForm,item:e.target.value})}/></label><div className="finance-v2__form-grid"><label><span>Cantidad proyectada</span><input value={budgetForm.projectedQuantity} onChange={(e)=>setBudgetForm({...budgetForm,projectedQuantity:e.target.value})}/></label><label><span>Cantidad confirmada</span><input value={budgetForm.confirmedQuantity} onChange={(e)=>setBudgetForm({...budgetForm,confirmedQuantity:e.target.value})}/></label></div><div className="finance-v2__form-grid"><label><span>Costo unitario neto</span><input type="number" min="0" value={budgetForm.unitNet??''} onChange={(e)=>setBudgetForm({...budgetForm,unitNet:num(e.target.value)})}/></label><label><span>IVA</span><select value={budgetForm.vat} onChange={(e)=>setBudgetForm({...budgetForm,vat:e.target.value})}><option value="0.19">19%</option><option value="0">0%</option><option value="">Por definir</option></select></label></div><div className="finance-v2__form-grid"><label><span>Total bruto manual</span><input type="number" min="0" value={budgetForm.projectedGross??''} onChange={(e)=>setBudgetForm({...budgetForm,projectedGross:num(e.target.value)})} placeholder="Vacío = cálculo automático"/></label><label><span>Anticipo</span><input type="number" min="0" value={budgetForm.advance??''} onChange={(e)=>setBudgetForm({...budgetForm,advance:num(e.target.value)})}/></label></div><div className="finance-v2__form-grid"><label><span>Categoría</span><input value={budgetForm.category} onChange={(e)=>setBudgetForm({...budgetForm,category:e.target.value})}/></label><label><span>Responsable</span><input value={budgetForm.responsible} onChange={(e)=>setBudgetForm({...budgetForm,responsible:e.target.value})}/></label></div><label><span>Estado</span><select value={budgetForm.status} onChange={(e)=>setBudgetForm({...budgetForm,status:e.target.value})}><option>Pendiente</option><option>En cotización</option><option>Confirmado</option><option>Pagado</option><option>Opcional</option></select></label><label><span>Observaciones</span><textarea rows={4} value={budgetForm.notes} onChange={(e)=>setBudgetForm({...budgetForm,notes:e.target.value})}/></label><footer><div>{!creating&&<button type="button" className="is-danger" onClick={deleteBudget} disabled={saving}><Trash2 size={13}/>Eliminar</button>}</div><div><button type="button" onClick={closeDrawer}>Cancelar</button><button type="submit" className="is-primary" disabled={saving}>{saving?<Loader2 size={13} className="animate-spin"/>:<Save size={13}/>}Guardar</button></div></footer></form>:
      drawer==='vendor'?<form onSubmit={saveVendor}><label><span>Nombre *</span><input value={vendorForm.name} onChange={(e)=>setVendorForm({...vendorForm,name:e.target.value})}/></label><div className="finance-v2__form-grid"><label><span>Categoría</span><input value={vendorForm.category||''} onChange={(e)=>setVendorForm({...vendorForm,category:e.target.value})}/></label><label><span>Estado</span><select value={vendorForm.status} onChange={(e)=>setVendorForm({...vendorForm,status:e.target.value})}><option>Evaluando</option><option>Contactado</option><option>Cotizando</option><option>Seleccionado</option><option>Contratado</option><option>Finalizado</option><option>Descartado</option></select></label></div><div className="finance-v2__form-grid"><label><span>Contacto</span><input value={vendorForm.contact_name||''} onChange={(e)=>setVendorForm({...vendorForm,contact_name:e.target.value})}/></label><label><span>Teléfono</span><input value={vendorForm.phone||''} onChange={(e)=>setVendorForm({...vendorForm,phone:e.target.value})}/></label></div><label><span>Email</span><input type="email" value={vendorForm.email||''} onChange={(e)=>setVendorForm({...vendorForm,email:e.target.value})}/></label><label><span>Notas</span><textarea rows={4} value={vendorForm.notes||''} onChange={(e)=>setVendorForm({...vendorForm,notes:e.target.value})}/></label><footer><div>{!creating&&<button type="button" className="is-danger" onClick={deleteVendor} disabled={saving}><Trash2 size={13}/>Eliminar</button>}</div><div><button type="button" onClick={closeDrawer}>Cancelar</button><button type="submit" className="is-primary" disabled={saving}>{saving?<Loader2 size={13} className="animate-spin"/>:<Save size={13}/>}Guardar</button></div></footer></form>:
      <form onSubmit={savePayment}><label><span>Concepto *</span><select value={paymentForm.expense_id} onChange={(e)=>setPaymentForm({...paymentForm,expense_id:e.target.value})}><option value="">Seleccionar registro de gasto…</option>{expenses.map((expense)=><option key={expense.id} value={expense.id}>{expense.concept}</option>)}</select></label><div className="finance-v2__form-grid"><label><span>Monto CLP *</span><input type="number" min="0" value={paymentForm.amount??''} onChange={(e)=>setPaymentForm({...paymentForm,amount:num(e.target.value)})}/></label><label><span>Fecha</span><input type="date" value={paymentForm.payment_date||''} onChange={(e)=>setPaymentForm({...paymentForm,payment_date:e.target.value})}/></label></div><div className="finance-v2__form-grid"><label><span>Medio</span><select value={paymentForm.payment_type||''} onChange={(e)=>setPaymentForm({...paymentForm,payment_type:e.target.value})}><option>Transferencia</option><option>Tarjeta</option><option>Efectivo</option><option>Otro</option></select></label><label><span>Estado</span><select value={paymentForm.status} onChange={(e)=>setPaymentForm({...paymentForm,status:e.target.value})}><option>Pendiente</option><option>Pagado</option><option>Anulado</option></select></label></div><label><span>Referencia</span><input value={paymentForm.reference||''} onChange={(e)=>setPaymentForm({...paymentForm,reference:e.target.value})}/></label><label><span>Notas</span><textarea rows={4} value={paymentForm.notes||''} onChange={(e)=>setPaymentForm({...paymentForm,notes:e.target.value})}/></label><footer><div>{!creating&&<button type="button" className="is-danger" onClick={deletePayment} disabled={saving}><Trash2 size={13}/>Eliminar</button>}</div><div><button type="button" onClick={closeDrawer}>Cancelar</button><button type="submit" className="is-primary" disabled={saving}>{saving?<Loader2 size={13} className="animate-spin"/>:<Save size={13}/>}Guardar</button></div></footer></form>}
    </aside></>}
  </div></DashboardLayout>;
}
