'use client';

export const dynamic = 'force-dynamic';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import DashboardLayout from '@/components/DashboardLayout';
import { createClient } from '@/lib/supabase-browser';
import { AlertCircle, Building2, CheckCircle2, DollarSign, Loader2, Plus, RefreshCw, WalletCards, X } from 'lucide-react';
import './finance-v2.css';

interface Vendor { id:string; name:string; category:string; contact_name:string|null; phone:string|null; email:string|null; status:string; notes:string|null; }
interface Expense { id:string; vendor_id:string|null; concept:string; category:string; currency:string; total_amount:number|null; payment_status:string; due_date:string|null; responsible:string|null; notes:string|null; }
interface Payment { id:string; expense_id:string; amount:number|null; currency:string; payment_date:string|null; payment_type:string|null; status:string; reference:string|null; notes:string|null; }
interface BudgetItem { rowNumber:number; item:string; projectedQuantity:string; confirmedQuantity:string; unitNet:number|null; vat:string; projectedGross:number|null; category:string; responsible:string; status:string; notes:string; advance:number|null; }
interface BudgetSource { ok:boolean; source:string; items:BudgetItem[]; summary:{paidOrPrepaid:number|null;remaining:number|null;totalBudget:number|null}; fetchedAt:string; error?:string; }
type Tab='budget'|'vendors'|'payments'; type Drawer='vendor'|'payment'|null; type Notice={type:'success'|'error'|'info';text:string};

function money(value:number|null|undefined){if(value===null||value===undefined)return 'Por confirmar';return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(value);}
function formatDate(value:string|null){if(!value)return 'Por definir';try{return new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric',timeZone:'America/Santiago'}).format(new Date(value));}catch{return value;}}

export default function FinancePage(){
  const [vendors,setVendors]=useState<Vendor[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[payments,setPayments]=useState<Payment[]>([]),[budget,setBudget]=useState<BudgetSource|null>(null);
  const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[tab,setTab]=useState<Tab>('budget'),[drawer,setDrawer]=useState<Drawer>(null),[notice,setNotice]=useState<Notice|null>(null),[previewMode,setPreviewMode]=useState(false);
  const [vForm,setVForm]=useState({name:'',category:'Locación',status:'Evaluando',contact_name:'',phone:'',email:'',notes:''});
  const [pForm,setPForm]=useState({expense_id:'',amount:'',payment_type:'Transferencia',status:'Pagado',notes:''});
  useEffect(()=>setPreviewMode(window.location.hostname!=='gestion.felipeycami.cl'),[]);
  const loadData=useCallback(async(manual=false)=>{if(manual)setRefreshing(true);setLoading(!manual);setNotice(null);try{const supabase=createClient();const [v,e,p,b]=await Promise.all([supabase.from('vendors').select('*').order('name'),supabase.from('expenses').select('*').order('created_at',{ascending:false}),supabase.from('expense_payments').select('*').order('created_at',{ascending:false}),fetch('/api/budget-source',{cache:'no-store'})]);const errors=[v.error,e.error,p.error].filter(Boolean);if(errors.length)throw new Error(errors.map((item)=>item?.message).join(' · '));const bp=await b.json().catch(()=>null);setVendors((v.data||[]) as Vendor[]);setExpenses((e.data||[]) as Expense[]);setPayments((p.data||[]) as Payment[]);if(b.ok&&bp?.ok)setBudget(bp as BudgetSource);else setNotice({type:'error',text:bp?.error||'No fue posible leer el presupuesto operativo.'});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible cargar finanzas.'});}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{loadData();},[loadData]);
  const paidSupabase=useMemo(()=>payments.filter((p)=>p.currency==='CLP'&&p.status==='Pagado').reduce((sum,p)=>sum+Number(p.amount||0),0),[payments]);
  const contractedVendors=vendors.filter((v)=>v.status==='Contratado').length;
  const budgetMissing=(budget?.items||[]).filter((item)=>item.projectedGross===null||(item.projectedGross===0&&item.unitNet===null)).length;

  async function addVendor(event:React.FormEvent){event.preventDefault();if(!vForm.name.trim())return;const draft:Vendor={id:`preview-vendor-${Date.now()}`,name:vForm.name.trim(),category:vForm.category,contact_name:vForm.contact_name||null,phone:vForm.phone||null,email:vForm.email||null,status:vForm.status,notes:vForm.notes||null};if(previewMode){setVendors((current)=>[...current,draft]);setDrawer(null);setNotice({type:'info',text:'Proveedor creado localmente en Preview. Producción permanece intacta.'});return;}try{const response=await fetch('/api/vendors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||'No fue posible crear proveedor.');setDrawer(null);await loadData();setNotice({type:'success',text:'Proveedor creado correctamente.'});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible crear proveedor.'});}}
  async function addPayment(event:React.FormEvent){event.preventDefault();if(!pForm.expense_id||!pForm.amount)return;const draft:Payment={id:`preview-payment-${Date.now()}`,expense_id:pForm.expense_id,amount:Number(pForm.amount),currency:'CLP',payment_date:new Date().toISOString().slice(0,10),payment_type:pForm.payment_type,status:pForm.status,reference:null,notes:pForm.notes||null};if(previewMode){setPayments((current)=>[draft,...current]);setDrawer(null);setNotice({type:'info',text:'Pago registrado localmente en Preview. Producción permanece intacta.'});return;}try{const response=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const payload=await response.json().catch(()=>({ok:response.ok}));if(!response.ok||payload.ok===false)throw new Error(payload.error||'No fue posible registrar pago.');setDrawer(null);await loadData();setNotice({type:'success',text:'Pago registrado correctamente.'});}catch(error:any){setNotice({type:'error',text:error?.message||'No fue posible registrar pago.'});}}

  return <DashboardLayout><div className="finance-v2">
    <section className="finance-v2__hero"><div><span className="finance-v2__eyebrow">Organización financiera</span><h1>Presupuesto y proveedores</h1><p>El presupuesto operativo se lee en vivo desde la hoja actual; proveedores y pagos estructurados se mantienen en Supabase mientras terminamos la migración financiera.</p></div><div className="finance-v2__actions">{previewMode&&<span className="finance-v2__preview">Preview · cambios locales</span>}<button type="button" onClick={()=>loadData(true)}><RefreshCw size={14} className={refreshing?'animate-spin':''}/>{refreshing?'Actualizando…':'Actualizar'}</button></div></section>
    {notice&&<div className={`finance-v2__notice finance-v2__notice--${notice.type}`}>{notice.type==='success'?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>}<span>{notice.text}</span></div>}
    <section className="finance-v2__source"><div><span>Fuente de presupuesto</span><strong>{budget?.source||'Cargando…'}</strong><small>lectura en vivo, sin duplicar cifras antiguas</small></div><div><span>Presupuesto total</span><strong>{money(budget?.summary.totalBudget)}</strong><small>según hoja operativa</small></div><div><span>Pagado / prepagado</span><strong>{money(budget?.summary.paidOrPrepaid)}</strong><small>según resumen de la hoja</small></div><div><span>Faltante</span><strong>{money(budget?.summary.remaining)}</strong><small>según resumen de la hoja</small></div></section>
    <section className="finance-v2__metrics"><article><span>Ítems presupuestados</span><strong>{budget?.items.length||0}</strong><small>{budgetMissing} con monto por completar</small></article><article><span>Proveedores Supabase</span><strong>{vendors.length}</strong><small>{contractedVendors} contratados</small></article><article><span>Pagos estructurados</span><strong>{payments.length}</strong><small>{money(paidSupabase)} registrados</small></article><article><span>Registros de gasto</span><strong>{expenses.length}</strong><small>migración desde presupuesto aún incompleta</small></article></section>
    <section className="finance-v2__toolbar"><div className="finance-v2__tabs"><button className={tab==='budget'?'is-active':''} onClick={()=>setTab('budget')}><WalletCards size={14}/>Presupuesto</button><button className={tab==='vendors'?'is-active':''} onClick={()=>setTab('vendors')}><Building2 size={14}/>Proveedores</button><button className={tab==='payments'?'is-active':''} onClick={()=>setTab('payments')}><DollarSign size={14}/>Pagos</button></div><div className="finance-v2__toolbar-actions">{tab==='vendors'&&<button onClick={()=>setDrawer('vendor')}><Plus size={13}/>Nuevo proveedor</button>}{tab==='payments'&&<button onClick={()=>setDrawer('payment')}><Plus size={13}/>Registrar pago</button>}</div></section>
    {loading?<div className="finance-v2__loading"><Loader2 className="animate-spin" size={20}/>Cargando fuentes financieras…</div>:tab==='budget'?<section className="finance-v2__budget"><div className="finance-v2__budget-head"><div><span>Ítem</span><span>Categoría</span><span>Responsable</span><span>Estado</span><span>Total proyectado</span></div></div><div className="finance-v2__budget-list">{(budget?.items||[]).map((item)=><article key={item.rowNumber}><div className="finance-v2__budget-name"><strong>{item.item}</strong><small>{item.notes||`${item.confirmedQuantity||item.projectedQuantity||'—'} unidades`}</small></div><span>{item.category||'—'}</span><span>{item.responsible||'—'}</span><span className="finance-v2__status">{item.status||'Sin estado'}</span><strong className={item.projectedGross===null?'is-missing':''}>{money(item.projectedGross)}</strong></article>)}</div></section>:tab==='vendors'?<section className="finance-v2__vendor-grid">{vendors.map((vendor)=><article key={vendor.id}><div className="finance-v2__vendor-top"><span><Building2 size={16}/></span><small>{vendor.status}</small></div><h2>{vendor.name}</h2><p>{vendor.category}</p><dl><div><dt>Contacto</dt><dd>{vendor.contact_name||'Por completar'}</dd></div><div><dt>Teléfono</dt><dd>{vendor.phone||'Por completar'}</dd></div><div><dt>Email</dt><dd>{vendor.email||'Por completar'}</dd></div></dl>{vendor.notes&&<footer>{vendor.notes}</footer>}</article>)}</section>:<section className="finance-v2__payments">{payments.map((payment)=>{const expense=expenses.find((item)=>item.id===payment.expense_id);return <article key={payment.id}><span className="finance-v2__payment-icon"><DollarSign size={15}/></span><div><strong>{expense?.concept||payment.payment_type||'Pago'}</strong><small>{formatDate(payment.payment_date)} · {payment.payment_type||'Sin medio'}</small></div><strong>{money(payment.amount)}</strong><span className="finance-v2__status">{payment.status}</span></article>})}{!payments.length&&<div className="finance-v2__empty">Aún no hay pagos estructurados.</div>}</section>}
    {drawer&&<><button type="button" className="finance-v2__backdrop" aria-label="Cerrar" onClick={()=>setDrawer(null)}/><aside className="finance-v2__drawer"><header><div><span className="finance-v2__eyebrow">{drawer==='vendor'?'Proveedores':'Pagos'}</span><h2>{drawer==='vendor'?'Nuevo proveedor':'Registrar pago'}</h2></div><button type="button" onClick={()=>setDrawer(null)}><X size={18}/></button></header>{drawer==='vendor'?<form onSubmit={addVendor}><label><span>Nombre *</span><input value={vForm.name} onChange={(e)=>setVForm({...vForm,name:e.target.value})}/></label><div className="finance-v2__form-grid"><label><span>Categoría</span><input value={vForm.category} onChange={(e)=>setVForm({...vForm,category:e.target.value})}/></label><label><span>Estado</span><select value={vForm.status} onChange={(e)=>setVForm({...vForm,status:e.target.value})}><option>Evaluando</option><option>Seleccionado</option><option>Contratado</option><option>Descartado</option></select></label></div><div className="finance-v2__form-grid"><label><span>Contacto</span><input value={vForm.contact_name} onChange={(e)=>setVForm({...vForm,contact_name:e.target.value})}/></label><label><span>Teléfono</span><input value={vForm.phone} onChange={(e)=>setVForm({...vForm,phone:e.target.value})}/></label></div><label><span>Email</span><input type="email" value={vForm.email} onChange={(e)=>setVForm({...vForm,email:e.target.value})}/></label><label><span>Notas</span><textarea rows={4} value={vForm.notes} onChange={(e)=>setVForm({...vForm,notes:e.target.value})}/></label><footer><button type="button" onClick={()=>setDrawer(null)}>Cancelar</button><button type="submit" className="is-primary">Guardar proveedor</button></footer></form>:<form onSubmit={addPayment}><label><span>Concepto *</span><select value={pForm.expense_id} onChange={(e)=>setPForm({...pForm,expense_id:e.target.value})}><option value="">Seleccionar registro de gasto…</option>{expenses.map((expense)=><option key={expense.id} value={expense.id}>{expense.concept}</option>)}</select></label><div className="finance-v2__form-grid"><label><span>Monto CLP *</span><input type="number" min="0" value={pForm.amount} onChange={(e)=>setPForm({...pForm,amount:e.target.value})}/></label><label><span>Medio</span><select value={pForm.payment_type} onChange={(e)=>setPForm({...pForm,payment_type:e.target.value})}><option>Transferencia</option><option>Tarjeta</option><option>Efectivo</option><option>Otro</option></select></label></div><label><span>Notas</span><textarea rows={4} value={pForm.notes} onChange={(e)=>setPForm({...pForm,notes:e.target.value})}/></label><footer><button type="button" onClick={()=>setDrawer(null)}>Cancelar</button><button type="submit" className="is-primary">Registrar pago</button></footer></form>}</aside></>}
  </div></DashboardLayout>;
}
